---
title: "10-3_Portland_distributional_analysis"
author: "Wei Shi"
date: "October 3, 2018"
output:
  word_document: default
  pdf_document:
    includes:
      in_header: header.tex
    number_sections: true
fig_width: 7
fig_height: 5
---

```{r setup,include=FALSE}

knitr::opts_chunk$set(cache = TRUE)
```

## load data

```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, tidyverse, dbplyr, stargazer,cowplot, lubridate, gridExtra)

#query the corridors from bike_lanes
user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)

source(here::here("Code/corridor_comparison_functions.R"))

portland_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, a.ce01 as ce01, a.ce02 as ce02, a.ce03 as ce03, a.cr01 as cr01,a.cr02 as cr02, a.cr03 as cr03, a.cr04 as cr04, a.cr05 as cr05, a.cr07 as cr07, a.cs02 as cs02, a.cd01 as cd01, a.cd02 as cd02, a.cd03 as cd03, a.cd04 as cd04, b.streetname as Name, b.type as Type, b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM portland_lehd a, portland_corridors b
WHERE ST_Intersects(ST_Buffer(b.geometry, 20), a.geometry);")

portland_corridor[portland_corridor$name =="EVERETT",]$type <- "Control: Everett"
portland_corridor[portland_corridor$name=="ALDER",]$type <- "Control: Alder"
portland_corridor[portland_corridor$name=="STARK_OAK",]$type <- "Treatment: Stark & Oak"
portland_corridor$type <- as.factor(portland_corridor$type)

portland_corridor <- portland_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04,
         Group=corridor_group, BuildStart = buildstart, BuildEnd = buildend, Name = name, Type=type)

portland_lehd <- st_read(dsn = con, query = "SELECT * FROM portland_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04)


portland_corridor_rac <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, a.ce01 as ce01, a.ce02 as ce02, a.ce03 as ce03, a.cr01 as cr01,a.cr02 as cr02, a.cr03 as cr03, a.cr04 as cr04, a.cr05 as cr05, a.cr07 as cr07, a.cs02 as cs02, a.cd01 as cd01, a.cd02 as cd02, a.cd03 as cd03, a.cd04 as cd04, b.streetname as Name, b.type as Type, b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM portland_rac a, portland_corridors b
WHERE ST_Intersects(ST_Buffer(b.geometry, 20), a.geometry);")

portland_corridor_rac[portland_corridor_rac$name =="EVERETT",]$type <- "Control: Everett"
portland_corridor_rac[portland_corridor_rac$name=="ALDER",]$type <- "Control: Alder"
portland_corridor_rac[portland_corridor_rac$name=="STARK_OAK",]$type <- "Treatment: Stark & Oak"
portland_corridor_rac$type <- as.factor(portland_corridor_rac$type)

portland_corridor_rac <- portland_corridor_rac %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04,
         Group=corridor_group, BuildStart = buildstart, BuildEnd = buildend, Name = name, Type=type)

portland_lehd <- st_read(dsn = con, query = "SELECT * FROM portland_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04)

portland_rac <- st_read(dsn = con, query = "SELECT * FROM portland_rac") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04)

portland_emp_ratio <- employ_ratio_test(portland_corridor)

portland_growth <- growth_rate(portland_corridor)

dbDisconnect(con)

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

```



# additional distributional analysis - income (bar graph)
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}
stark_inc <- portland_corridor %>% as.data.frame() %>% filter(Group == 1) %>% 
  mutate(Type = factor(Type, levels = c("Treatment: Stark & Oak", "Control: Alder", "Control: Everett"))) %>% 
  group_by(Type, year) %>% 
  summarise(low_income = sum(CE01), 
            mid_income = sum(CE02), 
            high_income = sum(CE03)) %>% 
  group_by(Type) %>% 
  gather(income_level, employment,low_income, mid_income, high_income) %>% 
  mutate(year = as.Date(as.character(paste0(year, "-01-01")),"%Y-%m-%d"),
         income_level = factor(income_level, levels=c("high_income", "mid_income", "low_income")),
         n = case_when(Type == "Treatment: Stark & Oak" ~ 38,
                       Type == "Control: Everett" ~30,
                       Type == "Control: Alder" ~ 25)) 

ggplot(data=stark_inc, aes(x=year, y=employment/n)) +
  geom_bar(aes(fill=income_level),stat = "identity")+
  facet_wrap(~Type)+
  scale_x_date(date_breaks = "3 years", date_labels = "%Y") +
  labs(title="Income Composition Trend Among Corridors", x="Year", y ="Employment per block", 
       caption = "Bike lane is constructed in 2009") +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name="Income Level",
                      breaks=c("high_income", "mid_income", "low_income"),
                      labels=c("High income", "Middle income", "Low income"))
  

```


# additional distributional analysis - race (line chart)
```{r echo=FALSE, fig.asp=1.5, fig.width=9.5, message=FALSE, warning=FALSE}
stark_race <- portland_corridor %>% as.data.frame() %>% filter(Group == 1) %>% 
  group_by(Type, year) %>% 
  summarise(
    white = sum(CR01), black = sum(CR02), ameindian = sum(CR03), asian = sum(CR04), 
    hawaii=sum(CR05), other=sum(CR07), tot_emp = sum(C000)) %>% 
  mutate(white_perc = white/tot_emp*100,
         black_perc = black/tot_emp*100,
         ameindian_perc = ameindian/tot_emp*100,
         asian_perc = asian/tot_emp*100,
         hawaii_perc = hawaii/tot_emp*100,
         other_perc = other/tot_emp*100) 

pdx_race <- portland_lehd %>% 
  group_by(year) %>% 
  summarise(
    white = sum(CR01), black = sum(CR02), ameindian = sum(CR03), asian = sum(CR04), 
    hawaii=sum(CR05), other=sum(CR07), tot_emp = sum(C000)) %>% 
  mutate(white_perc = white/tot_emp*100,
         black_perc = black/tot_emp*100,
         ameindian_perc = ameindian/tot_emp*100,
         asian_perc = asian/tot_emp*100,
         hawaii_perc = hawaii/tot_emp*100,
         other_perc = other/tot_emp*100,
         Type = "City") %>% 
  select(Type, year:other_perc)


stark_race <- rbind(as.data.frame(stark_race), as.data.frame(pdx_race))
stark_race[stark_race$year<2009,][,c(3:8,10:15)] <- NA
stark_race$Type <- as.factor(as.character(stark_race$Type))
  

white_plot <- dist_trend_plot(stark_race,demo = "White", demo_code = "white_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010, 86, 90)

black_plot <- dist_trend_plot(stark_race,demo = "Black", demo_code = "black_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010, 1,5)

ameindian_plot <- dist_trend_plot(stark_race,demo = "American Indian", demo_code = "ameindian_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment",construct_year = 2009, end_year = 2010, 0,4)

asian_plot <- dist_trend_plot(stark_race,demo = "Asian", demo_code = "asian_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010,3,7)

hawaii_plot <- dist_trend_plot(stark_race,demo = "Native Hawaiian", demo_code = "hawaii_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010,0,4)

other_plot <- dist_trend_plot(stark_race,demo = "Two or More Races", demo_code = "other_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010,0,4)

mylegend<-g_legend(white_plot)

grid.arrange(arrangeGrob(white_plot + theme(legend.position="none"), black_plot + theme(legend.position="none"),
                         asian_plot + theme(legend.position="none"), ameindian_plot + theme(legend.position="none"),
                         hawaii_plot + theme(legend.position="none"), other_plot + theme(legend.position="none"),
                         nrow=3),
             mylegend, nrow=4,heights=c(10, 1,1,1))
```


# additional distributional analysis - race (table)
```{r}
start_end_race <- stark_race %>%
  select(Type, year, ends_with("_perc")) %>% # select variables ends with "_perc"
  filter(complete.cases(.)) %>%
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_perc")), funs(change = (last(.)-first(.))/first(.)/6*100))

  
# calculate year by year race categories percentage change  
y_o_y_race <- stark_race %>% 
  select(Type, year, ends_with("_perc")) %>% 
  mutate_if(is.numeric, funs(change = ./lag(.)*100 -100)) %>% 
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_change")), funs(mean(., na.rm=T)))

```

# additional distributional analysis - education (line chart)
```{r echo=FALSE, fig.asp=1, fig.width=9.5, message=FALSE, warning=FALSE}
stark_edu <- portland_corridor %>% as.data.frame() %>% filter(Group == 1) %>% 
  group_by(Type, year) %>% 
  summarise(
    hisch_under = sum(CD01), hisch = sum(CD02), col = sum(CD03), bach = sum(CD04), tot_emp = sum(C000)) %>% 
  mutate(hisch_under_perc = hisch_under/tot_emp*100,
         hisch_perc = hisch/tot_emp*100,
         col_perc = col/tot_emp*100,
         bach_perc = bach/tot_emp*100) 

pdx_edu <- portland_lehd %>% 
  group_by(year) %>% 
  summarise(
    hisch_under = sum(CD01), hisch = sum(CD02), col = sum(CD03), bach = sum(CD04), tot_emp = sum(C000)) %>% 
  mutate(hisch_under_perc = hisch_under/tot_emp*100,
         hisch_perc = hisch/tot_emp*100,
         col_perc = col/tot_emp*100,
         bach_perc = bach/tot_emp*100,
         Type = "City") %>% 
  select(Type, year:bach_perc)


stark_edu <- rbind(as.data.frame(stark_edu), as.data.frame(pdx_edu))
stark_edu[stark_edu$year<2009,][,c(3:6,8:11)] <- NA
stark_edu$Type <- as.factor(as.character(stark_edu$Type))
  

hisch_under_plot <- dist_trend_plot(stark_edu,demo = "Less Than High School", demo_code = "hisch_under_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010, 0, 10)

hisch_plot <- dist_trend_plot(stark_edu,demo = "High School", demo_code = "hisch_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010, 10, 20)

col_plot <- dist_trend_plot(stark_edu,demo = "College", demo_code = "col_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010, 20, 30)

bach_plot <- dist_trend_plot(stark_edu,demo = "Bachelor or Above", demo_code = "bach_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010,27.6,37.6)

mylegend<-g_legend(hisch_plot)

grid.arrange(arrangeGrob(hisch_under_plot + theme(legend.position="none"), hisch_plot + theme(legend.position="none"),
                         col_plot + theme(legend.position="none"), bach_plot + theme(legend.position="none"),
                         nrow=2),
             mylegend, nrow=3,heights=c(10, 1,1))
```

# additional distributional analysis - edu (table)
```{r}
start_end_edu <- stark_edu %>%
  select(Type, year, ends_with("_perc")) %>% # select variables ends with "_perc"
  filter(complete.cases(.)) %>%
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_perc")), funs(change = (last(.)-first(.))/first(.)/6*100))
  
  
# calculate year by year race categories percentage change  
y_o_y_edu <- stark_edu %>% 
  select(Type, year, ends_with("_perc")) %>% 
  mutate_if(is.numeric, funs(change = ./lag(.)*100 -100)) %>% 
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_change")), funs(mean(., na.rm=T)))
```


# distributional rac - race table
```{r echo=FALSE, fig.asp=1.5, fig.width=9.5, message=FALSE, warning=FALSE}
stark_race <- portland_corridor_rac %>% as.data.frame() %>% filter(Group == 1) %>% 
  group_by(Type, year) %>% 
  summarise(
    white = sum(CR01), black = sum(CR02), ameindian = sum(CR03), asian = sum(CR04), 
    hawaii=sum(CR05), other=sum(CR07), tot_emp = sum(C000)) %>% 
  mutate(white_perc = white/tot_emp*100,
         black_perc = black/tot_emp*100,
         ameindian_perc = ameindian/tot_emp*100,
         asian_perc = asian/tot_emp*100,
         hawaii_perc = hawaii/tot_emp*100,
         other_perc = other/tot_emp*100) 

pdx_race <- portland_rac %>% 
  group_by(year) %>% 
  summarise(
    white = sum(CR01), black = sum(CR02), ameindian = sum(CR03), asian = sum(CR04), 
    hawaii=sum(CR05), other=sum(CR07), tot_emp = sum(C000)) %>% 
  mutate(white_perc = white/tot_emp*100,
         black_perc = black/tot_emp*100,
         ameindian_perc = ameindian/tot_emp*100,
         asian_perc = asian/tot_emp*100,
         hawaii_perc = hawaii/tot_emp*100,
         other_perc = other/tot_emp*100,
         Type = "City") %>% 
  select(Type, year:other_perc)


stark_race <- rbind(as.data.frame(stark_race), as.data.frame(pdx_race))
stark_race[stark_race$year<2009,][,c(3:8,10:15)] <- NA
stark_race$Type <- as.factor(as.character(stark_race$Type))

white_plot <- dist_trend_plot(stark_race,demo = "White", demo_code = "white_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010, 79, 91)

black_plot <- dist_trend_plot(stark_race,demo = "Black", demo_code = "black_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010, 1,13)

ameindian_plot <- dist_trend_plot(stark_race,demo = "American Indian", demo_code = "ameindian_perc", corridor_name = "Stark & Oak Avenue",cat = "Residents", construct_year = 2009, end_year = 2010, 0,12)

asian_plot <- dist_trend_plot(stark_race,demo = "Asian", demo_code = "asian_perc", corridor_name = "Stark & Oak Avenue",cat = "Residents", construct_year = 2009, end_year = 2010,0,12)

hawaii_plot <- dist_trend_plot(stark_race,demo = "Native Hawaiian", demo_code = "hawaii_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010,0,12)

other_plot <- dist_trend_plot(stark_race,demo = "Two or More Races", demo_code = "other_perc", corridor_name = "Stark & Oak Avenue",cat = "Residents", construct_year = 2009, end_year = 2010,0,12)

mylegend<-g_legend(white_plot)

grid.arrange(arrangeGrob(white_plot + theme(legend.position="none"), black_plot + theme(legend.position="none"),
                         asian_plot + theme(legend.position="none"), ameindian_plot + theme(legend.position="none"),
                         hawaii_plot + theme(legend.position="none"), other_plot + theme(legend.position="none"),
                         nrow=3),
             mylegend, nrow=4,heights=c(10, 1,1,1))

start_end_race <- stark_race %>%
  select(Type, year, ends_with("_perc")) %>% # select variables ends with "_perc"
  filter(complete.cases(.)) %>%
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_perc")), funs(change = (last(.)-first(.))/first(.)/6*100))
  
  
# calculate year by year race categories percentage change  
y_o_y_race <- stark_race %>% 
  select(Type, year, ends_with("_perc")) %>% 
  mutate_if(is.numeric, funs(change = ./lag(.)*100 -100)) %>% 
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_change")), funs(mean(., na.rm=T)))

```

      
# distributional rac - edu table
```{r echo=FALSE, fig.asp=1, fig.width=9.5, message=FALSE, warning=FALSE}
stark_edu <- portland_corridor_rac %>% as.data.frame() %>% filter(Group == 1) %>% 
  group_by(Type, year) %>% 
  summarise(
    hisch_under = sum(CD01), hisch = sum(CD02), col = sum(CD03), bach = sum(CD04), tot_emp = sum(C000)) %>% 
  mutate(hisch_under_perc = hisch_under/tot_emp*100,
         hisch_perc = hisch/tot_emp*100,
         col_perc = col/tot_emp*100,
         bach_perc = bach/tot_emp*100) 

pdx_edu <- portland_rac %>% 
  group_by(year) %>% 
  summarise(
    hisch_under = sum(CD01), hisch = sum(CD02), col = sum(CD03), bach = sum(CD04), tot_emp = sum(C000)) %>% 
  mutate(hisch_under_perc = hisch_under/tot_emp*100,
         hisch_perc = hisch/tot_emp*100,
         col_perc = col/tot_emp*100,
         bach_perc = bach/tot_emp*100,
         Type = "City") %>% 
  select(Type, year:bach_perc)


stark_edu <- rbind(as.data.frame(stark_edu), as.data.frame(pdx_edu))
stark_edu[stark_edu$year<2009,][,c(3:6,8:11)] <- NA
stark_edu$Type <- as.factor(as.character(stark_edu$Type))

hisch_under_plot <- dist_trend_plot(stark_edu,demo = "Less Than High School", demo_code = "hisch_under_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010, 0, 15)

hisch_plot <- dist_trend_plot(stark_edu,demo = "High School", demo_code = "hisch_perc", corridor_name = "Stark & Oak Avenue", cat = "Redidents", construct_year = 2009, end_year = 2010, 10, 25)

col_plot <- dist_trend_plot(stark_edu,demo = "College", demo_code = "col_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010, 12, 27)

bach_plot <- dist_trend_plot(stark_edu,demo = "Bachelor or Above", demo_code = "bach_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010,20,35)

mylegend<-g_legend(hisch_plot)

grid.arrange(arrangeGrob(hisch_under_plot + theme(legend.position="none"), hisch_plot + theme(legend.position="none"),
                         col_plot + theme(legend.position="none"), bach_plot + theme(legend.position="none"),
                         nrow=2),
             mylegend, nrow=3,heights=c(10, 1,1))
  
start_end_edu <- stark_edu %>%
  select(Type, year, ends_with("_perc")) %>% # select variables ends with "_perc"
  filter(complete.cases(.)) %>%
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_perc")), funs(change = (last(.)-first(.))/first(.)/6*100))
  
  
# calculate year by year race categories percentage change  
y_o_y_edu <- stark_edu %>% 
  select(Type, year, ends_with("_perc")) %>% 
  mutate_if(is.numeric, funs(change = ./lag(.)*100 -100)) %>% 
  group_by(Type) %>% 
  summarise_at(vars(ends_with("_change")), funs(mean(., na.rm=T))) 

```


# gender
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}
stark_gender <- portland_corridor %>% as.data.frame() %>% filter(Group == 1) %>% 
  group_by(Type, year) %>% 
  summarise(female = sum(CS02), tot_emp = sum(C000)) %>% 
  mutate(female_perc = female/tot_emp*100) 

pdx_gender <- portland_lehd %>% 
  group_by(year) %>% 
  summarise(female = sum(CS02), tot_emp = sum(C000)) %>% 
  mutate(female_perc = female/tot_emp*100,
         Type = "City") %>% 
  select(Type, year:female_perc)

stark_gender <- rbind(as.data.frame(stark_gender), as.data.frame(pdx_gender))
stark_gender[stark_gender$year<2009,][,c(3,5)] <- NA
stark_gender$Type <- as.factor(as.character(stark_gender$Type))

gender_plot <- dist_trend_plot(stark_gender,demo = "Female", demo_code = "female_perc", corridor_name = "Stark & Oak Avenue", cat = "Employment", construct_year = 2009, end_year = 2010, 30, 60)

stark_gender_rac <- portland_corridor_rac %>% as.data.frame() %>% filter(Group == 1) %>% 
  group_by(Type, year) %>% 
  summarise(female = sum(CS02), tot_emp = sum(C000)) %>% 
  mutate(female_perc = female/tot_emp*100) 

pdx_gender_rac <- portland_rac %>% 
  group_by(year) %>% 
  summarise(female = sum(CS02), tot_emp = sum(C000)) %>% 
  mutate(female_perc = female/tot_emp*100,
         Type = "City") %>% 
  select(Type, year:female_perc)

stark_gender_rac <- rbind(as.data.frame(stark_gender_rac), as.data.frame(pdx_gender_rac))
stark_gender_rac[stark_gender_rac$year<2009,][,c(3,5)] <- NA
stark_gender_rac$Type <- as.factor(as.character(stark_gender_rac$Type))

gender_rac_plot <- dist_trend_plot(stark_gender_rac,demo = "Female", demo_code = "female_perc", corridor_name = "Stark & Oak Avenue", cat = "Residents", construct_year = 2009, end_year = 2010, 30, 60)



mylegend<-g_legend(gender_plot)

grid.arrange(arrangeGrob(gender_plot + theme(legend.position="none"), gender_rac_plot + theme(legend.position="none"),
                         nrow = 1),
             mylegend, nrow=2,heights=c(10,1))
```
