---
title: "6-4_Minneapolis_Sales_data"
author: "Wei Shi"
date: "June 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Sales
```{r echo=FALSE, message=FALSE, warning=FALSE}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, stargazer, sf, ggplot2, ggthemes, cowplot, dplyr,tidyr)

source(here::here("Code/corridor_comparison_functions.R"))

minn_sale <- read.csv(here::here("Data/Minneapolis/BikeDataAggregated.csv"))

minn_sale <- minn_sale %>% 
  filter(!is.na(Street)) %>%
  mutate(Group= case_when(Street %in% c("RIVERSIDE AVE","CEDAR AVE S") ~ 1,
                          Street=="FRANKLIN AVE E" ~ 2,
                          Street %in% c("CENTRAL AVE NE","UNIVERSITY AVE NE") ~3,
                          Street %in% c("LYNDALE AVE S","GRAND AVE S") ~4,
                          Street %in% c("2ND ST N","WEST BROADWAY") ~5),
         Study= case_when(Group==1 ~ ifelse(Street=="RIVERSIDE AVE"," Improvement","Control"),
                          Group==2 ~ ifelse(Street=="FRANKLIN AVE E"," Improvement","Control"),
                         Group==3 ~ ifelse(Street=="CENTRAL AVE NE"," Improvement","Control"),
                         Group==4 ~ ifelse(Street=="LYNDALE AVE S"," Improvement","Control"),
                         Group==5 ~ ifelse(Street=="2ND ST N"," Improvement","Control"))
         ) %>% 
  filter(Group %in% c(1:5)) %>% 
  group_by(Street,Type,Group,Study,TaxYear) %>% 
  summarise(TaxableSales = sum(TaxableSales, na.rm = TRUE))

minn_sale <- minn_sale %>% 
  spread(Type,TaxableSales) %>% 
  mutate(year=TaxYear,
         Type=Study,
         CNS07=Retail,
         CNS18=Restaurant,
         geometry=1)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}
riverside_agg <- agg_index_trend_table (minn_sale, group = 1,2009)

riverside_agg_retail_plot <- ggplot(riverside_agg,aes(x=year, y=CNS07_sd,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2009, xmax = 2010, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Retail Sales Comparison: Riverside Ave", x="Year",y="Sale Index",
       caption = "Sales tax is indexed to 2009 \n Shaded Area is Construction Period")

riverside_agg_accom_plot <- ggplot(riverside_agg,aes(x=year, y=CNS18_sd,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2009, xmax = 2010, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Resturaunt Sales Comparison: Riverside Ave", x="Year",y="Sale Index",
       caption = "Sales tax is indexed to 2009 \n Shaded Area is Construction Period")

# riverside_agg_retail_plot <- agg_index_trend_plot(riverside_agg, industry = "Retail", corridor_name = "Riverside Ave.",industry_code = "CNS07_sd", construct_year = 2009, end_year = 2010)

# riverside_agg_accom_plot <- agg_index_trend_plot(riverside_agg, industry = "Accommodations", corridor_name = "Riverside Ave.",industry_code = "CNS18_sd", construct_year = 2009, end_year = 2010)

plot_grid(riverside_agg_retail_plot, riverside_agg_accom_plot, align = "h")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}
central_agg <- agg_index_trend_table (minn_sale, group = 3,2012)

central_agg_retail_plot <- ggplot(central_agg,aes(x=year, y=CNS07_sd,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2012, xmax = 2013, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Retail Sales Comparison: Central Ave", x="Year",y="Sale Index",
       caption = "Sales tax is indexed to 2012 \n Shaded Area is Construction Period")

central_agg_accom_plot <- ggplot(central_agg,aes(x=year, y=CNS18_sd,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2012, xmax = 2013, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Resturaunt Sales Comparison: Central Ave", x="Year",y="Sale Index",
       caption = "Sales tax is indexed to 2012 \n Shaded Area is Construction Period")

# central_agg_retail_plot <- agg_index_trend_plot(central_agg, industry = "Retail", corridor_name = "central Ave.",industry_code = "CNS07_sd", construct_year = 2009, end_year = 2010)

# central_agg_accom_plot <- agg_index_trend_plot(central_agg, industry = "Accommodations", corridor_name = "central Ave.",industry_code = "CNS18_sd", construct_year = 2009, end_year = 2010)

plot_grid(central_agg_retail_plot, central_agg_accom_plot, align = "h")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}
lyndale_agg <- agg_index_trend_table (minn_sale, group = 4,2008)

lyndale_agg_retail_plot <- ggplot(lyndale_agg,aes(x=year, y=CNS07_sd,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2008, xmax = 2009, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Retail Sales Comparison: Lyndale Ave", x="Year",y="Sale Index",
       caption = "Sales tax is indexed to 2008 \n Shaded Area is Construction Period")

lyndale_agg_accom_plot <- ggplot(lyndale_agg,aes(x=year, y=CNS18_sd,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2008, xmax = 2009, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Resturaunt Sales Comparison: Lyndale Ave", x="Year",y="Sale Index",
       caption = "Sales tax is indexed to 2008 \n Shaded Area is Construction Period")

# lyndale_agg_retail_plot <- agg_index_trend_plot(lyndale_agg, industry = "Retail", corridor_name = "lyndale Ave.",industry_code = "CNS07_sd", construct_year = 2009, end_year = 2010)

# lyndale_agg_accom_plot <- agg_index_trend_plot(lyndale_agg, industry = "Accommodations", corridor_name = "lyndale Ave.",industry_code = "CNS18_sd", construct_year = 2009, end_year = 2010)

plot_grid(lyndale_agg_retail_plot, lyndale_agg_accom_plot, align = "h")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}
second_agg <- agg_index_trend_table (minn_sale, group = 5,2011)
second_agg <- agg_trend_table (minn_sale, group = 5)

second_agg_retail_plot <- ggplot(second_agg,aes(x=year, y=CNS07,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2011, xmax = 2012, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Retail Sales Comparison: North Second Ave", x="Year",y="Sale Index",
       caption = "Shaded Area is Construction Period")

second_agg_accom_plot <- ggplot(second_agg,aes(x=year, y=CNS18,group=Type,colour=Type,shape=Type))+
  geom_rect(aes(xmin = 2011, xmax = 2012, ymin = -Inf, ymax = Inf),fill = "darkolivegreen1",linetype=0,alpha = 0.03) +
  geom_line() + 
  geom_point(size=3, fill="white") +
  scale_shape_manual(values=c(22,21))+
  scale_x_continuous(breaks=c(2004,2006,2008,2010,2012,2014,2016)) +
  theme_minimal() +
  labs(title = "Resturaunt Sales Comparison: second Ave", x="Year",y="Sale Index",
       caption = "Shaded Area is Construction Period")

# second_agg_retail_plot <- agg_index_trend_plot(second_agg, industry = "Retail", corridor_name = "second Ave.",industry_code = "CNS07_sd", construct_year = 2009, end_year = 2010)

# second_agg_accom_plot <- agg_index_trend_plot(second_agg, industry = "Accommodations", corridor_name = "second Ave.",industry_code = "CNS18_sd", construct_year = 2009, end_year = 2010)

plot_grid(second_agg_retail_plot, second_agg_accom_plot, align = "h")

```