---
title: "8-16_Memphis_NETS_Analysis"
author: "Minji Cho"
date: "May 23, 2019"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load data
```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, tidyverse, dbplyr, stargazer,cowplot, lubridate, gridExtra,data.table, dplyr, zoo, tidyr, kableExtra, data.table, bindrcpp, knitr)

user <- "minji2"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)


source(here::here("Code/corridor_comparison_functions.R"))

memphis_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, a.ce01 as ce01, a.ce02 as ce02, a.ce03 as ce03, a.cr01 as cr01,a.cr02 as cr02, a.cr03 as cr03, a.cr04 as cr04, a.cr05 as cr05, a.cr07 as cr07, a.cs02 as cs02, a.cd01 as cd01, a.cd02 as cd02, a.cd02 as cd03, a.cd04 as cd04, b.name as Name, b.type as Type, b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM memphis_lehd a, memhpis_corridors b
WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

cooper <- memphis_corridor %>% filter(name == "Cooper Street") %>% mutate(corridor_group=1)

memphis_corridor <-rbind(memphis_corridor, cooper)

memphis_corridor <- memphis_corridor[memphis_corridor$name!="Jackson Avenue",]

memphis_corridor$Type <- ifelse(is.na(memphis_corridor$buildstart),"Control", "Treatment")
memphis_corridor[memphis_corridor$name=="Madison Avenue",]$Type <- "Treatment: Madison"
memphis_corridor[memphis_corridor$name=="Broad Avenue",]$Type <- "Treatment: Broad"
memphis_corridor[memphis_corridor$name=="Central Avenue",]$Type <- "Control: Central"
memphis_corridor[memphis_corridor$name=="Cooper Street",]$Type <- "Control: Cooper"
memphis_corridor[memphis_corridor$name=="Highland Street",]$Type <- "Control: Highland"
memphis_corridor[memphis_corridor$name=="Union Avenue",]$Type <- "Control: Union"
memphis_corridor$Type <- as.factor(memphis_corridor$Type)

memphis_corridor <- memphis_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, Group = corridor_group,
         BuildStart = buildstart, BuildEnd = buildend, Name = name)

memphis_lehd <- st_read(dsn = con, query = "SELECT * FROM memphis_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19)

memphis_emp_ratio <- employ_ratio_test(memphis_corridor)

memphis_growth <- growth_rate(memphis_corridor)

memphis_sales <- tbl(con, "memphis_sales_tax") %>% 
  collect()%>% 
  mutate(year = format(pctym, "%Y"),
         Type = paste(street_type, district_name, sep=": ")) %>% 
  group_by(year,district_name, street_type, street_group, Type) %>% 
  summarise(business = mean(businesses),
            gross_sales = sum(gross_sales))
  

memphis_qcew <- tbl(con, "memphis_qcew") %>% collect() %>% mutate(street_group = as.character(street_group))

# exclude Jackson corridor which is not comparable to treatment corridor
memphis_qcew <- memphis_qcew[memphis_qcew$district_name!="Jackson Ave",]

memphis_qcew$Type <- as.factor(memphis_qcew$Type)


# load nets
memphis_nets <- st_read(dsn = con, query = "select * FROM nets") %>% filter(city =="MEMPHIS")

memphis_blocks <- left_join(as.data.frame(memphis_corridor), unique(memphis_lehd[,c(1,56)]), by =c("geoid" = "geoid10")) %>% 
  mutate(geometry.x=NULL, geometry=geometry.y, geometry.y=NULL) %>% st_sf

memphis_nets_b <- st_join(memphis_nets, unique(memphis_blocks[,c(26:30,32)]) %>% st_sf, join=st_intersects, left=F) %>% select(-"type") 
names(memphis_nets_b)  <- tolower(names(memphis_nets_b))

# memphis_nets_bf <- st_read(dsn = con, query = "select * FROM nets a, memphis_corridors b WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

memphis_c <-  st_read(dsn = con, "memhpis_corridors")
cooper_c <- st_read(dsn = con,"memhpis_corridors") %>% filter(name=="Cooper Street") %>% mutate(group=1)
memphis_c <-rbind(memphis_c, cooper_c)

memphis_nets_bf <- st_intersection(memphis_nets, st_buffer(memphis_c, 20)) %>% select(-id, -start, -end, -shape_leng)

memphis_nets_bf <- memphis_nets_bf[memphis_nets_bf$name!="Jackson Avenue",]

memphis_nets_bf[memphis_nets_bf$name=="Madison Avenue",]$type <- "Treatment: Madison"
memphis_nets_bf[memphis_nets_bf$name=="Broad Avenue",]$type <- "Treatment: Broad"
memphis_nets_bf[memphis_nets_bf$name=="Central Avenue",]$type <- "Control: Central"
memphis_nets_bf[memphis_nets_bf$name=="Cooper Street",]$type <- "Control: Cooper"
memphis_nets_bf[memphis_nets_bf$name=="Highland Street",]$type <- "Control: Highland"
memphis_nets_bf[memphis_nets_bf$name=="Union Avenue",]$type <- "Control: Union"

memphis_madison_b <- memphis_nets_b %>% 
  filter(group==1) %>% 
  gather(key, value, -c(1:10,89:97)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
memphis_madison_bf <- memphis_nets_bf %>% 
  filter(group==1) %>% 
  gather(key, value, -c(1:10,89:99)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
memphis_broad_b <- memphis_nets_b %>% 
  filter(group==2) %>% 
  gather(key, value, -c(1:10,89:97)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
memphis_broad_bf <- memphis_nets_bf %>% 
  filter(group==2) %>% 
  gather(key, value, -c(1:10,89:99)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 

nets <- setDT(memphis_nets)
nets <- setkey(nets, dunsnumber)
nets_long <- melt(nets, id.vars = c("dunsnumber", "city"),
                  measure.vars = 11:88,
                  variable.factor = TRUE)

memphis_nets_a <- nets_long %>% 
  separate(variable, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))

memphis_nets1 <- memphis_nets_a %>% 
  group_by(year, biz1) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T)/1000000, n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)

memphis_nets2 <- memphis_nets_a %>% 
  group_by(year, biz2) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T)/1000000, n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)


dbDisconnect(con)

```

# NETS analysis: Broad Avenue
## trend plot - industry type 1
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}

# one types of industry categories similar to LEHD
broad_nets_b <- memphis_broad_b %>% 
  group_by(name, type, buildstart, buildend, group, year, biz1) %>% 
  summarise(emp = sum(emp), sales= sum(sales)/1000000, n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% filter(biz1=="Food"| biz1== "Retail") %>%
 as.data.frame(.) %>% select(-geometry)

memphis_nets1 <- memphis_nets1 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=2) %>% select(name:group, year:sales_pest) %>% as.data.frame()

broad_nets_b <- rbind(broad_nets_b, memphis_nets1) %>% mutate(geometry=0)

# employment plot
# abousolute employment
broad_nets1_emp <- broad_nets_b %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, emp) %>%
  rename(CNS07 = Retail, CNS18 = Food, Group = group, Type = type)
broad_nets1_emp $Type <- as.factor(broad_nets1_emp$Type)

broad_emp_retail_trend_plot <- trend_plot(filter(broad_nets1_emp, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                          corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                          y_lable = "Employment", index = "Total", unit="")

broad_emp_food_trend_plot <- trend_plot(filter(broad_nets1_emp, Type!="City"& year>2003), industry = "Food",industry_code = "CNS18",
                                        corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                        y_lable = "Employment", index = "Total", unit="")


# employment per establishment
broad_nets1_emp_pest <- broad_nets_b %>% select(-sales, -n, -emp, -sales_pest) %>% spread(key = biz1, emp_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group = group, Type = type)
broad_nets1_emp_pest$Type <- as.factor(as.character(broad_nets1_emp_pest$Type))

broad_emp_pest_retail_trend_plot <- trend_plot(filter(broad_nets1_emp_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                               corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                               y_lable = "Employment", index = "Per Establishment", unit="")

broad_emp_pest_food_trend_plot <- trend_plot(filter(broad_nets1_emp_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                             corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                             y_lable = "Employment", index = "Per Establishment", unit="")


# indexed employment
broad_nets1_emp_idx <- agg_index_trend_table(broad_nets1_emp, group = 2, construct_year = 2010)
broad_nets1_emp_idx$Type <- as.factor(as.character(broad_nets1_emp_idx$Type))

broad_emp_retail_indexed_trend_plot <- trend_plot(filter(broad_nets1_emp_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                  corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                  y_lable = "Employment", index = "Indexed", unit="")

broad_emp_food_indexed_trend_plot <- trend_plot(filter(broad_nets1_emp_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                y_lable = "Employment", index = "Indexed", unit="")

prow <- plot_grid(broad_emp_retail_trend_plot + theme(legend.position="none"),
                  broad_emp_food_trend_plot + theme(legend.position="none"),
                  broad_emp_pest_retail_trend_plot + theme(legend.position="none"),
                  broad_emp_pest_food_trend_plot + theme(legend.position="none"),
                  broad_emp_retail_indexed_trend_plot + theme(legend.position="none"),
                  broad_emp_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(broad_emp_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))



# sales plot
# abousolute sales
broad_nets1_sales <- broad_nets_b %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)

broad_nets1_sales$Type <- as.factor(broad_nets1_sales$Type)

broad_sales_retail_trend_plot <- trend_plot(filter(broad_nets1_sales, Type!="City"& year>2003), industry = "Retail", industry_code = "CNS07",
                                            corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                            y_lable = "Sales", index = "Total", unit = "(in millions)")

broad_sales_food_trend_plot <- trend_plot(filter(broad_nets1_sales, Type!="City"& year>2003), industry = "Food",industry_code = "CNS18",
                                          corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                          y_lable = "Sales", index = "Total", unit = "(in millions)")


# sales per establishment
broad_nets1_sales_pest <- broad_nets_b %>% select(-sales, -n, -emp, -emp_pest) %>% spread(key = biz1, sales_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
broad_nets1_sales_pest$Type <- as.factor(as.character(broad_nets1_sales_pest$Type))

broad_sales_pest_retail_trend_plot <- trend_plot(filter(broad_nets1_sales_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                                 corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                 y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")

broad_sales_pest_food_trend_plot <- trend_plot(filter(broad_nets1_sales_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                               corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                               y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")

# indexed sales
broad_nets1_sales_idx <- agg_index_trend_table(broad_nets1_sales, group = 2, construct_year = 2010)
broad_nets1_sales_idx $Type <- as.factor(as.character(broad_nets1_sales_idx$Type))

broad_sales_retail_indexed_trend_plot <- trend_plot(filter(broad_nets1_sales_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                    corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                    y_lable = "Sales", index = "Indexed", unit="")

broad_sales_food_indexed_trend_plot <- trend_plot(filter(broad_nets1_sales_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                  corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                  y_lable = "Sales", index = "Indexed", unit="")

prow <- plot_grid(broad_sales_retail_trend_plot + theme(legend.position="none"),
                  broad_sales_food_trend_plot + theme(legend.position="none"),
                  broad_sales_pest_retail_trend_plot + theme(legend.position="none"),
                  broad_sales_pest_food_trend_plot + theme(legend.position="none"),
                  broad_sales_retail_indexed_trend_plot + theme(legend.position="none"),
                  broad_sales_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(broad_sales_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

## trend plot - industry type 2
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}

# one types of industry categories only with block face establishments
broad_nets_bf <- memphis_broad_bf %>% 
  mutate(buildstart = as.numeric(buildstart), buildend=as.numeric(buildend)) %>% 
  mutate(buildstart = ifelse(is.na(buildstart), 0, buildstart),
         buildend = ifelse(is.na(buildend), 0, buildend)) %>% 
  group_by(name, type, buildstart, buildend, group, year, biz2) %>% 
  summarise(emp = sum(emp), sales= sum(sales)/1000000, n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)
  
memphis_nets2 <- memphis_nets2 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=2) %>% select(name:group, year:sales_pest)

broad_nets_bf <- rbind(broad_nets_bf, memphis_nets2) %>% mutate(geometry=0)

# employment plot
# abousolute employment
broad_nets2_emp <- broad_nets_bf %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
broad_nets2_emp $Type <- as.factor(broad_nets2_emp $Type)

broad_emp_retail_trend_plot <- trend_plot(filter(broad_nets2_emp, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                          corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                          y_lable = "Employment", index = "Total", unit="")

broad_emp_food_trend_plot <- trend_plot(filter(broad_nets2_emp, Type!="City" & year>2003), industry = "Food",industry_code = "CNS18",
                                        corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                        y_lable = "Employment", index = "Total", unit="")

# employment per establishment
broad_nets2_emp_pest <- broad_nets_bf %>% select(-sales, -n, -emp, -sales_pest) %>% spread(key = biz2, emp_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
broad_nets2_emp_pest $Type <- as.factor(broad_nets2_emp_pest $Type)

broad_emp_pest_retail_trend_plot <- trend_plot(filter(broad_nets2_emp_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                               corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                               y_lable = "Employment", index = "Per Establishment", unit="")

broad_emp_pest_food_trend_plot <- trend_plot(filter(broad_nets2_emp_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                             corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                             y_lable = "Employment", index = "Per Establishment", unit="")


# indexed employment
broad_nets2_emp_idx <- agg_index_trend_table(broad_nets2_emp, group = 2, construct_year = 2010)
broad_nets2_emp_idx$Type <- as.factor(broad_nets2_emp_idx$Type)

broad_emp_retail_indexed_trend_plot <- trend_plot(filter(broad_nets2_emp_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                  corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                  y_lable = "Employment", index = "Indexed", unit="")

broad_emp_food_indexed_trend_plot <- trend_plot(filter(broad_nets2_emp_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                y_lable = "Employment", index = "Indexed", unit="")

prow <- plot_grid(broad_emp_retail_trend_plot + theme(legend.position="none"),
                  broad_emp_food_trend_plot + theme(legend.position="none"),
                  broad_emp_pest_retail_trend_plot + theme(legend.position="none"),
                  broad_emp_pest_food_trend_plot + theme(legend.position="none"),
                  broad_emp_retail_indexed_trend_plot + theme(legend.position="none"),
                  broad_emp_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(broad_emp_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(2, .2))


# sales plot
# abousolute sales
broad_nets2_sales <- broad_nets_bf %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
broad_nets2_sales $Type <- as.factor(broad_nets2_sales$Type)

broad_sales_retail_trend_plot <- trend_plot(filter(broad_nets2_sales, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                            corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                            y_lable = "Sales", index = "Total", unit = "(in millions)")

broad_sales_food_trend_plot <- trend_plot(filter(broad_nets2_sales, Type!="City" & year>2003), industry = "Food",industry_code = "CNS18",
                                          corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                          y_lable = "Sales", index = "Total", unit = "(in millions)")


# sales per establishment
broad_nets2_sales_pest <- broad_nets_bf %>% select(-sales, -n, -emp, -emp_pest) %>% spread(key = biz2, sales_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
broad_nets2_sales_pest$Type <- as.factor(broad_nets2_sales_pest$Type)

broad_sales_pest_retail_trend_plot <- trend_plot(filter(broad_nets2_sales_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                                 corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                 y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")

broad_sales_pest_food_trend_plot <- trend_plot(filter(broad_nets2_sales_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                               corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                               y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")


# indexed sales
broad_nets2_sales_idx <- agg_index_trend_table(broad_nets2_sales, group = 2, construct_year = 2010)
broad_nets2_sales_idx$Type <- as.factor(broad_nets2_sales_idx$Type)

broad_sales_retail_indexed_trend_plot <- trend_plot(filter(broad_nets2_sales_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                    corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                    y_lable = "Sales", index = "Indexed", unit="")

broad_sales_food_indexed_trend_plot <- trend_plot(filter(broad_nets2_sales_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                  corridor_name = "Broad Avenue", construct_year = 2010, end_year = 2011,
                                                  y_lable = "Sales", index = "Indexed", unit="")

prow <- plot_grid(broad_sales_retail_trend_plot + theme(legend.position="none"),
                  broad_sales_food_trend_plot + theme(legend.position="none"),
                  broad_sales_pest_retail_trend_plot + theme(legend.position="none"),
                  broad_sales_pest_food_trend_plot + theme(legend.position="none"),
                  broad_sales_retail_indexed_trend_plot + theme(legend.position="none"),
                  broad_sales_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(broad_sales_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```



# model
```{r, echo=FALSE, results='asis'}
# DID
#employment
broad_nets1_emp$Type <- relevel(broad_nets1_emp$Type,ref = "Treatment: Broad")
broad_nets2_emp$Type <- relevel(broad_nets2_emp$Type,ref = "Treatment: Broad")

broad_nets1_emp_did <- did_agg_analysis(filter(broad_nets1_emp, Type!="City" & year>2003), group = 2, endyear = 2010)
broad_nets2_emp_did <- did_agg_analysis(filter(broad_nets2_emp, Type!="City" & year>2003), group = 2, endyear = 2010)
stargazer(broad_nets1_emp_did[[1]], broad_nets2_emp_did[[1]], broad_nets1_emp_did[[2]], broad_nets2_emp_did[[2]],
          broad_nets1_emp_did[[3]], broad_nets2_emp_did[[3]],
          title = "Broad Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2", "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business"), model.numbers = F)

# sales
broad_nets1_sales$Type <- relevel(broad_nets1_sales$Type,ref = "Treatment: Broad")
broad_nets2_sales$Type <- relevel(broad_nets2_sales$Type,ref = "Treatment: Broad")

broad_nets1_sales_did <- did_agg_analysis(filter(broad_nets1_sales, Type!="City" & year>2003), group = 2, endyear = 2010)
broad_nets2_sales_did <- did_agg_analysis(filter(broad_nets2_sales, Type!="City" & year>2003), group = 2, endyear = 2010)
stargazer(broad_nets1_sales_did[[1]], broad_nets2_sales_did[[1]], broad_nets1_sales_did[[2]], broad_nets2_sales_did[[2]], 
          title = "Broad Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

# show only Type 1 results
stargazer(broad_nets1_emp_did[[1]], broad_nets1_emp_did[[2]], broad_nets1_emp_did[[3]],
          broad_nets1_sales_did[[1]],  broad_nets1_sales_did[[2]], broad_nets1_sales_did[[3]],
          title = "Broad Avenue Corridor Difference-in-Difference Estimates (block)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

# show only Type 2 results
stargazer(broad_nets2_emp_did[[1]], broad_nets2_emp_did[[2]], broad_nets2_emp_did[[3]],
          broad_nets2_sales_did[[1]],  broad_nets2_sales_did[[2]], broad_nets2_sales_did[[3]],
          title = "Broad Avenue Corridor Difference-in-Difference Estimates (buffer)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

# ITS
broad_nets1_emp <- broad_nets1_emp %>%
  mutate(Type = ifelse(Type=="Treatment: Broad", "Treatment", as.character(Type)))
broad_nets2_emp <- broad_nets2_emp %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Broad", "Treatment", as.character(Type)))
broad_nets1_sales <- broad_nets1_sales %>% 
  mutate(Type = ifelse(Type=="Treatment: Broad", "Treatment", as.character(Type)))
broad_nets2_sales <- broad_nets2_sales %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Broad", "Treatment", as.character(Type)))

broad_nets1_emp_its <- agg_its_analysis(filter(broad_nets1_emp, Type!="City" & year>2003), group = 2, endyear = 2010)
broad_nets2_emp_its <- agg_its_analysis(filter(broad_nets2_emp, Type!="City" & year>2003), group = 2, endyear = 2010)
stargazer(broad_nets1_emp_its[[1]], broad_nets2_emp_its[[1]], broad_nets1_emp_its[[2]], broad_nets2_emp_its[[2]], 
          broad_nets1_emp_its[[3]], broad_nets2_emp_its[[3]],
          title = "Broad Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2",  "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business Emp."), model.numbers = F)


broad_nets1_sales_its <- agg_its_analysis(filter(broad_nets1_sales, Type!="City" & year>2003), group = 2, endyear = 2010)
broad_nets2_sales_its <- agg_its_analysis(filter(broad_nets2_sales, Type!="City" & year>2003), group = 2, endyear = 2010)
stargazer(broad_nets1_sales_its[[1]], broad_nets2_sales_its[[1]], broad_nets1_sales_its[[2]], broad_nets2_sales_its[[2]], 
          title = "Broad Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

stargazer(broad_nets1_emp_its[[1]], broad_nets1_emp_its[[2]], broad_nets1_emp_its[[3]],
          broad_nets1_sales_its[[1]],  broad_nets1_sales_its[[2]], broad_nets1_sales_its[[3]],
          title = "Broad Avenue Corridor Interrupted Time Series Estimates (block)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

stargazer(broad_nets2_emp_its[[1]], broad_nets2_emp_its[[2]], broad_nets2_emp_its[[3]],
          broad_nets2_sales_its[[1]],  broad_nets2_sales_its[[2]], broad_nets2_sales_its[[3]],
          title = "Broad Avenue Corridor Interrupted Time Series Estimates (buffer)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)


```


# NETS analysis: Madison Avenue
## trend plot - industry type 1
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}

# one types of industry categories similar to LEHD
madison_nets_b <- memphis_madison_b %>% 
  group_by(name, type, buildstart, buildend, group, year, biz1) %>% 
  summarise(emp = sum(emp), sales= sum(sales)/1000000, n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% filter(biz1=="Food"| biz1== "Retail") %>%
 as.data.frame(.) %>% select(-geometry)

memphis_nets1 <- memphis_nets1 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=1) %>% select(name:group, year:sales_pest) %>% as.data.frame()

madison_nets_b <- rbind(madison_nets_b, memphis_nets1) %>% mutate(geometry=0)

# employment plot
# abousolute employment
madison_nets1_emp <- madison_nets_b %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, emp) %>%
  rename(CNS07 = Retail, CNS18 = Food, Group = group, Type = type)
madison_nets1_emp $Type <- as.factor(madison_nets1_emp$Type)

madison_emp_retail_trend_plot <- trend_plot(filter(madison_nets1_emp, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                          corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                          y_lable = "Employment", index = "Total", unit="")

madison_emp_food_trend_plot <- trend_plot(filter(madison_nets1_emp, Type!="City" & year>2003), industry = "Food",industry_code = "CNS18",
                                        corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                        y_lable = "Employment", index = "Total", unit="")


# employment per establishment
madison_nets1_emp_pest <- madison_nets_b %>% select(-sales, -n, -emp, -sales_pest) %>% spread(key = biz1, emp_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group = group, Type = type)
madison_nets1_emp_pest$Type <- as.factor(as.character(madison_nets1_emp_pest$Type))

madison_emp_pest_retail_trend_plot <- trend_plot(filter(madison_nets1_emp_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                               corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                               y_lable = "Employment", index = "Per Establishment", unit="")

madison_emp_pest_food_trend_plot <- trend_plot(filter(madison_nets1_emp_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                             corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                             y_lable = "Employment", index = "Per Establishment", unit="")


# indexed employment
madison_nets1_emp_idx <- agg_index_trend_table(madison_nets1_emp, group = 1, construct_year = 2011)
madison_nets1_emp_idx$Type <- as.factor(as.character(madison_nets1_emp_idx$Type))

madison_emp_retail_indexed_trend_plot <- trend_plot(filter(madison_nets1_emp_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                  corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                  y_lable = "Employment", index = "Indexed", unit="")

madison_emp_food_indexed_trend_plot <- trend_plot(filter(madison_nets1_emp_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                y_lable = "Employment", index = "Indexed", unit="")

prow <- plot_grid(madison_emp_retail_trend_plot + theme(legend.position="none"),
                  madison_emp_food_trend_plot + theme(legend.position="none"),
                  madison_emp_pest_retail_trend_plot + theme(legend.position="none"),
                  madison_emp_pest_food_trend_plot + theme(legend.position="none"),
                  madison_emp_retail_indexed_trend_plot + theme(legend.position="none"),
                  madison_emp_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(madison_emp_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))



# sales plot
# abousolute sales
madison_nets1_sales <- madison_nets_b %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
madison_nets1_sales$Type <- as.factor(madison_nets1_sales$Type)

madison_sales_retail_trend_plot <- trend_plot(filter(madison_nets1_sales, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                            corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                            y_lable = "Sales", index = "Total", unit = "(in millions)")

madison_sales_food_trend_plot <- trend_plot(filter(madison_nets1_sales, Type!="City" & year>2003), industry = "Food",industry_code = "CNS18",
                                          corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                          y_lable = "Sales", index = "Total", unit = "(in millions)")


# sales per establishment
madison_nets1_sales_pest <- madison_nets_b %>% select(-sales, -n, -emp, -emp_pest) %>% spread(key = biz1, sales_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
madison_nets1_sales_pest$Type <- as.factor(as.character(madison_nets1_sales_pest$Type))

madison_sales_pest_retail_trend_plot <- trend_plot(filter(madison_nets1_sales_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                                 corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                 y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")

madison_sales_pest_food_trend_plot <- trend_plot(filter(madison_nets1_sales_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                               corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                               y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")

# indexed sales
madison_nets1_sales_idx <- agg_index_trend_table(madison_nets1_sales, group = 1, construct_year = 2011)
madison_nets1_sales_idx $Type <- as.factor(as.character(madison_nets1_sales_idx$Type))

madison_sales_retail_indexed_trend_plot <- trend_plot(filter(madison_nets1_sales_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                    corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                    y_lable = "Sales", index = "Indexed", unit="")

madison_sales_food_indexed_trend_plot <- trend_plot(filter(madison_nets1_sales_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                  corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                  y_lable = "Sales", index = "Indexed", unit="")

prow <- plot_grid(madison_sales_retail_trend_plot + theme(legend.position="none"),
                  madison_sales_food_trend_plot + theme(legend.position="none"),
                  madison_sales_pest_retail_trend_plot + theme(legend.position="none"),
                  madison_sales_pest_food_trend_plot + theme(legend.position="none"),
                  madison_sales_retail_indexed_trend_plot + theme(legend.position="none"),
                  madison_sales_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(madison_sales_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

## trend plot - industry type 2
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}

# one types of industry categories only with block face establishments
madison_nets_bf <- memphis_madison_bf %>% 
  mutate(buildstart = as.numeric(buildstart), buildend=as.numeric(buildend)) %>% 
  mutate(buildstart = ifelse(is.na(buildstart), 0, buildstart),
         buildend = ifelse(is.na(buildend), 0, buildend)) %>% 
  group_by(name, type, buildstart, buildend, group, year, biz2) %>% 
  summarise(emp = sum(emp), sales= sum(sales)/1000000, n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)
  
memphis_nets2 <- memphis_nets2 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=1) %>% select(name:group, year:sales_pest)

madison_nets_bf <- rbind(madison_nets_bf, memphis_nets2) %>% mutate(geometry=0)

# employment plot
# abousolute employment
madison_nets2_emp <- madison_nets_bf %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
madison_nets2_emp $Type <- as.factor(madison_nets2_emp $Type)

madison_emp_retail_trend_plot <- trend_plot(filter(madison_nets2_emp, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                          corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                          y_lable = "Employment", index = "Total")

madison_emp_food_trend_plot <- trend_plot(filter(madison_nets2_emp, Type!="City" & year>2003), industry = "Food",industry_code = "CNS18",
                                        corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                        y_lable = "Employment", index = "Total")

# employment per establishment
madison_nets2_emp_pest <- madison_nets_bf %>% select(-sales, -n, -emp, -sales_pest) %>% spread(key = biz2, emp_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
madison_nets2_emp_pest $Type <- as.factor(madison_nets2_emp_pest $Type)

madison_emp_pest_retail_trend_plot <- trend_plot(filter(madison_nets2_emp_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                               corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                               y_lable = "Employment", index = "Per Establishment")

madison_emp_pest_food_trend_plot <- trend_plot(filter(madison_nets2_emp_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                             corridor_name = "madison Avenue", construct_year = 2011, end_year = 2012,
                                             y_lable = "Employment", index = "Per Establishment")


# indexed employment
madison_nets2_emp_idx <- agg_index_trend_table(madison_nets2_emp, group = 1, construct_year = 2011)
madison_nets2_emp_idx$Type <- as.factor(madison_nets2_emp_idx$Type)

madison_emp_retail_indexed_trend_plot <- trend_plot(filter(madison_nets2_emp_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                  corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                  y_lable = "Employment", index = "Indexed")

madison_emp_food_indexed_trend_plot <- trend_plot(filter(madison_nets2_emp_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                y_lable = "Employment", index = "Indexed")

prow <- plot_grid(madison_emp_retail_trend_plot + theme(legend.position="none"),
                  madison_emp_food_trend_plot + theme(legend.position="none"),
                  madison_emp_pest_retail_trend_plot + theme(legend.position="none"),
                  madison_emp_pest_food_trend_plot + theme(legend.position="none"),
                  madison_emp_retail_indexed_trend_plot + theme(legend.position="none"),
                  madison_emp_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(madison_emp_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(2, .2))


# sales plot
# abousolute sales
madison_nets2_sales <- madison_nets_bf %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
madison_nets2_sales $Type <- as.factor(madison_nets2_sales$Type)

madison_sales_retail_trend_plot <- trend_plot(filter(madison_nets2_sales, Type!="City" & year>2003), industry = "Retail", industry_code = "CNS07",
                                            corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                            y_lable = "Sales", index = "Total", unit = "(in millions)")

madison_sales_food_trend_plot <- trend_plot(filter(madison_nets2_sales, Type!="City" & year>2003), industry = "Food",industry_code = "CNS18",
                                          corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                          y_lable = "Sales", index = "Total", unit = "(in millions)")


# sales per establishment
madison_nets2_sales_pest <- madison_nets_bf %>% select(-sales, -n, -emp, -emp_pest) %>% spread(key = biz2, sales_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
madison_nets2_sales_pest$Type <- as.factor(madison_nets2_sales_pest$Type)

madison_sales_pest_retail_trend_plot <- trend_plot(filter(madison_nets2_sales_pest, year>2003), industry = "Retail", industry_code = "CNS07_pest",
                                                 corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                 y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")

madison_sales_pest_food_trend_plot <- trend_plot(filter(madison_nets2_sales_pest, year>2003), industry = "Food",industry_code = "CNS18_pest",
                                               corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                               y_lable = "Sales", index = "Per Establishment", unit = "(in millions)")


# indexed sales
madison_nets2_sales_idx <- agg_index_trend_table(madison_nets2_sales, group = 1, construct_year = 2011)
madison_nets2_sales_idx$Type <- as.factor(madison_nets2_sales_idx$Type)

madison_sales_retail_indexed_trend_plot <- trend_plot(filter(madison_nets2_sales_idx, year>2003), industry = "Retail", industry_code = "CNS07_sd",
                                                    corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                    y_lable = "Sales", index = "Indexed")

madison_sales_food_indexed_trend_plot <- trend_plot(filter(madison_nets2_sales_idx, year>2003), industry = "Food",industry_code = "CNS18_sd",
                                                  corridor_name = "Madison Avenue", construct_year = 2011, end_year = 2012,
                                                  y_lable = "Sales", index = "Indexed")

prow <- plot_grid(madison_sales_retail_trend_plot + theme(legend.position="none"),
                  madison_sales_food_trend_plot + theme(legend.position="none"),
                  madison_sales_pest_retail_trend_plot + theme(legend.position="none"),
                  madison_sales_pest_food_trend_plot + theme(legend.position="none"),
                  madison_sales_retail_indexed_trend_plot + theme(legend.position="none"),
                  madison_sales_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(madison_sales_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

## trend analysis - table
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}

# compute post change table compare to base year
madison_nets1_emp %>% 
  filter (year %in% c(2012, 2013, 2014, 2015)) %>% 
  group_by(name) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)

madison_nets1_sales %>% 
  filter (year %in% c(2012, 2013, 2014, 2015)) %>% 
  group_by(name) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)

madison_nets2_emp %>% 
  filter (year %in% c(2012, 2013, 2014, 2015)) %>% 
  group_by(name) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)

madison_nets2_sales %>% 
  filter (year %in% c(2012, 2013, 2014, 2015)) %>% 
  group_by(name) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)
  
```

# model
```{r, echo=FALSE, results='asis'}
# DID
#employment
madison_nets1_emp$Type <- relevel(madison_nets1_emp$Type,ref = "Treatment: Madison")
madison_nets2_emp$Type <- relevel(madison_nets2_emp$Type,ref = "Treatment: Madison")

madison_nets1_emp_did <- did_agg_analysis(filter(madison_nets1_emp, Type!="City" & year>2003), group = 1, endyear = 2011)
madison_nets2_emp_did <- did_agg_analysis(filter(madison_nets2_emp, Type!="City" & year>2003), group = 1, endyear = 2011)
stargazer(madison_nets1_emp_did[[1]], madison_nets2_emp_did[[1]], madison_nets1_emp_did[[2]], madison_nets2_emp_did[[2]],
          madison_nets1_emp_did[[3]], madison_nets2_emp_did[[3]],
          title = "Madison Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2", "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business"), model.numbers = F)

# sales
madison_nets1_sales$Type <- relevel(madison_nets1_sales$Type,ref = "Treatment: Madison")
madison_nets2_sales$Type <- relevel(madison_nets2_sales$Type,ref = "Treatment: Madison")

madison_nets1_sales_did <- did_agg_analysis(filter(madison_nets1_sales, Type!="City" & year>2003), group = 1, endyear = 2011)
madison_nets2_sales_did <- did_agg_analysis(filter(madison_nets2_sales, Type!="City" & year>2003), group = 1, endyear = 2011)
stargazer(madison_nets1_sales_did[[1]], madison_nets2_sales_did[[1]], madison_nets1_sales_did[[2]], madison_nets2_sales_did[[2]], 
          title = "Madison Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

# show only Type 1 results
stargazer(madison_nets1_emp_did[[1]], madison_nets1_emp_did[[2]], madison_nets1_emp_did[[3]],
          madison_nets1_sales_did[[1]],  madison_nets1_sales_did[[2]], madison_nets1_sales_did[[3]],
          title = "Madison Avenue Corridor Difference-in-Difference Estimates (block)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

# show only Type 2 results
stargazer(madison_nets2_emp_did[[1]], madison_nets2_emp_did[[2]], madison_nets2_emp_did[[3]],
          madison_nets2_sales_did[[1]],  madison_nets2_sales_did[[2]], madison_nets2_sales_did[[3]],
          title = "Madison Avenue Corridor Difference-in-Difference Estimates (buffer)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

# ITS
madison_nets1_emp <- madison_nets1_emp %>%
  mutate(Type = ifelse(Type=="Treatment: Madison", "Treatment", as.character(Type)))
madison_nets2_emp <- madison_nets2_emp %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Madison", "Treatment", as.character(Type)))
madison_nets1_sales <- madison_nets1_sales %>% 
  mutate(Type = ifelse(Type=="Treatment: Madison", "Treatment", as.character(Type)))
madison_nets2_sales <- madison_nets2_sales %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Madison", "Treatment", as.character(Type)))

madison_nets1_emp_its <- agg_its_analysis(filter(madison_nets1_emp, Type!="City" & year>2003), group = 1, endyear = 2011)
madison_nets2_emp_its <- agg_its_analysis(filter(madison_nets2_emp, Type!="City" & year>2003), group = 1, endyear = 2011)
stargazer(madison_nets1_emp_its[[1]], madison_nets2_emp_its[[1]], madison_nets1_emp_its[[2]], madison_nets2_emp_its[[2]], 
          madison_nets1_emp_its[[3]], madison_nets2_emp_its[[3]],
          title = "Madison Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2",  "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business Emp."), model.numbers = F)


madison_nets1_sales_its <- agg_its_analysis(filter(madison_nets1_sales, Type!="City" & year>2003), group = 1, endyear = 2011)
madison_nets2_sales_its <- agg_its_analysis(filter(madison_nets2_sales, Type!="City" & year>2003), group = 1, endyear = 2011)
stargazer(madison_nets1_sales_its[[1]], madison_nets2_sales_its[[1]], madison_nets1_sales_its[[2]], madison_nets2_sales_its[[2]], 
          title = "Madison Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "html", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

stargazer(madison_nets1_emp_its[[1]], madison_nets1_emp_its[[2]], madison_nets1_emp_its[[3]],
          madison_nets1_sales_its[[1]],  madison_nets1_sales_its[[2]], madison_nets1_sales_its[[3]],
          title = "Madison Avenue Corridor Interrupted Time Series Estimates (block)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

stargazer(madison_nets2_emp_its[[1]], madison_nets2_emp_its[[2]], madison_nets2_emp_its[[3]],
          madison_nets2_sales_its[[1]],  madison_nets2_sales_its[[2]], madison_nets2_sales_its[[3]],
          title = "Madison Avenue Corridor Interrupted Time Series Estimates (buffer)", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)


```

# functions
```{r message=FALSE, warning=FALSE, include=FALSE}

percent <- function(x, digits = 2, format = "f", ...) {
paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}

nets_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df$name <- as.factor(df$name)
  df$year <- as.numeric(df$year)
  
  base <- filter(df, year%in%(base_start:base_end)& Type!="City") %>% 
    group_by(name) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
         CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    bind_rows(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
          select(year, name, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
  group_by(name) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), name ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  nets <- merge(base, post, by="name") %>% 
    select(name, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(name)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(nets)<-coln

  return(nets)
}

plot_t <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  group_rows("NETS: (employment, type1)", 1,2) %>%
  group_rows("NETS: (employment, type2)", 3,4) %>%
  group_rows("NETS: (sales, type1)", 5,6) %>%
  group_rows("NETS: (sales, type2)", 7,8) %>%
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))

  return(plot)

}

plot_tc <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

  return(plot)
}

```

# madison
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

nets1e <- nets_t(madison_nets1_emp, 2011)
nets1s <- nets_t(madison_nets1_sales, 2011)
nets2e <- nets_t(madison_nets2_emp, 2011)
nets2s <- nets_t(madison_nets2_sales, 2011)

# make combined table         
t <- rbind(nets1e, nets1s, nets2e, nets2s)
t[t=="NaN"]<-NA
t[t==0]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,5,9,13),background="#ccffcc") %>% 
  group_rows("NETS: (employment, type1)",1,4) %>%
  group_rows("NETS: (employment, type2)", 5,8) %>%
  group_rows("NETS: (sales, type1)", 9,12) %>%
  group_rows("NETS: (sales, type2)", 13,16) %>%
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
                      "Pre-growth rate is defined as average of baseline annual growth rate;",
                      "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))


```


# broad
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

nets1e <- nets_t(broad_nets1_emp, 2010)
nets1s <- nets_t(broad_nets1_sales, 2010)
nets2e <- nets_t(broad_nets2_emp, 2010)
nets2s <- nets_t(broad_nets2_sales, 2010)

# make combined table         
t <- rbind(nets1e, nets1s, nets2e, nets2s)
t[t=="NaN"]<-NA
t[t==0]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,4,7),background="#ccffcc") %>% 
  group_rows("NETS: (employment, type1)", 1,3) %>%
  group_rows("NETS: (employment, type2)", 4,6) %>%
  group_rows("NETS: (sales, type1)", 7,9) %>%
  group_rows("NETS: (sales, type2)", 10,12) %>%
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))


```

