---
title: "Portland_corridors"
author: "Wei Shi"
date: "August 30, 2018"
output:
  word_document: default
  pdf_document:
    includes:
      in_header: header.tex
    number_sections: true
fig_width: 7
fig_height: 5
---

```{r setup,include=FALSE}

knitr::opts_chunk$set(cache = TRUE)
```

## load data

```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, tidyverse, dbplyr, stargazer,cowplot, lubridate, gridExtra,data.table)

#query the corridors from bike_lanes
user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)

source(here::here("Code/corridor_comparison_functions.R"))

portland_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, a.ce01 as ce01, a.ce02 as ce02, a.ce03 as ce03, a.cr01 as cr01,a.cr02 as cr02, a.cr03 as cr03, a.cr04 as cr04, a.cr05 as cr05, a.cr07 as cr07, a.cs02 as cs02, a.cd01 as cd01, a.cd02 as cd02, a.cd02 as cd03, a.cd04 as cd04, b.streetname as Name, b.type as Type, b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM portland_lehd a, portland_corridors b
WHERE ST_Intersects(ST_Buffer(b.geometry, 20), a.geometry);")

portland_corridor[portland_corridor$name =="STARK_OAK",]$type <- "Treatment: Stark & Oak"
portland_corridor[portland_corridor$name =="EVERETT",]$type <- "Control: Everett"
portland_corridor[portland_corridor$name=="ALDER",]$type <- "Control: Alder"
portland_corridor$type <- as.factor(portland_corridor$type)

portland_corridor <- portland_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04,
         Group=corridor_group, BuildStart = buildstart, BuildEnd = buildend, Name = name, Type=type)

portland_lehd <- st_read(dsn = con, query = "SELECT * FROM portland_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04)

portland_emp_ratio <- employ_ratio_test(portland_corridor)

portland_growth <- growth_rate(portland_corridor)

# load nets
pdx_nets <- st_read(dsn = con, query = "select * FROM nets") %>% filter(city =="PORTLAND")

pdx_blocks <- left_join(as.data.frame(portland_corridor), unique(portland_lehd[,c(1,56)]), by =c("geoid" = "geoid10")) %>% 
  mutate(geometry.x=NULL, geometry=geometry.y, geometry.y=NULL) %>% st_sf

pdx_nets_b <- st_join(pdx_nets, unique(pdx_blocks[,c(26:30,32)]) %>% st_sf, join=st_intersects, left=F)  
names(pdx_nets_b)  <- tolower(names(pdx_nets_b))

pdx_nets_bf <- st_read(dsn = con, query = "select * FROM nets a, portland_corridors b
WHERE ST_Intersects(ST_Buffer(b.geometry, 20), a.geometry);")

pdx_nets_bf[pdx_nets_bf$streetname=="STARK_OAK",]$type <- "Treatment: Stark & Oak"
pdx_nets_bf[pdx_nets_bf$streetname =="EVERETT",]$type <- "Control: Everett"
pdx_nets_bf[pdx_nets_bf$streetname=="ALDER",]$type <- "Control: Alder"

 pdx_stark_b <- pdx_nets_b %>% 
  filter(group==1) %>% 
  gather(key, value, -c(1:10,89:97)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
 pdx_stark_bf <- pdx_nets_bf %>% 
  filter(group==1) %>% 
  gather(key, value, -c(1:10,89:99)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year))) %>% 
   select(-c("objectid", shape_leng))
 

nets <- setDT(pdx_nets)
nets <- setkey(nets, dunsnumber)
nets_long <- melt(nets, id.vars = c("dunsnumber", "city"),
                  measure.vars = 11:88,
                  variable.factor = TRUE)

pdx_nets_a <- nets_long %>% 
  separate(variable, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))

pdx_nets1 <- pdx_nets_a %>% 
  group_by(year, biz1) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)

pdx_nets2 <- pdx_nets_a %>% 
  group_by(year, biz2) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)


dbDisconnect(con)

```


# corridor comparison
```{r message=FALSE, warning=FALSE, include=FALSE}

#comparisons-----

# prepare city level data & block level corridor data at the year before construction
conyear <- first(filter(portland_corridor, Group== 1, Type== "Treatment")$BuildStart)-1 
# find the year before construction

portland_lehd_2008 <- portland_lehd %>% filter(year == conyear, CNS07+ CNS18 > 0)

stark <- portland_corridor %>% filter(Group ==1, Type =="Treatment", year==conyear) %>% employ_ratio_test(.)

alder <- portland_corridor %>% filter(Group ==1, Type =="Control: Alder", year ==conyear) %>% employ_ratio_test(.)

everett <- portland_corridor %>% filter(Group ==1, Type =="Control: Everett", year ==conyear) %>% employ_ratio_test(.)


# find quantile dataframe 

p <- seq(0,1, by = .05)

quant_df <- data.frame(q_tot_emp = quantile(portland_lehd_2008$C000, probs = p, na.rm = TRUE),
                       q_retail = quantile(portland_lehd_2008$CNS07, probs = p, na.rm = TRUE),
                       q_food_accom = quantile(portland_lehd_2008$CNS18, probs = p, na.rm = TRUE),
                       probs = p)

stark %>% summarise(TotEmp = sum(C000)/nrow(stark), RetailEmp = sum(CNS07)/nrow(stark),
                                     AccomEmp = sum(CNS18)/nrow(stark)) %>% as.data.frame()
alder %>% summarise(TotEmp = sum(C000)/nrow(alder), RetailEmp = sum(CNS07)/nrow(alder),
                                     AccomEmp = sum(CNS18)/nrow(alder)) %>% as.data.frame
everett %>% summarise(TotEmp = sum(C000)/nrow(everett), RetailEmp = sum(CNS07)/nrow(everett),
                                     AccomEmp = sum(CNS18)/nrow(everett)) %>% as.data.frame
# get employment at block level, divided by nrow()
 

# t-test: compare retail, food_accom, business amount---
t.test(stark$Business, alder$Business)
t.test(stark$Retail, alder$Retail)
t.test(stark$Food_Accom, alder$Food_Accom)
t.test(stark$ratio1, alder$ratio1)
t.test(stark$ratio2, alder$ratio2)

t.test(stark$Business, everett$Business) # sig
t.test(stark$Retail, everett$Retail)
t.test(stark$Food_Accom, everett$Food_Accom) # sig
t.test(stark$ratio1, everett$ratio1)
t.test(stark$ratio2, everett$ratio2)


# t-tests: growth rate----

stark_growth <- portland_growth %>%  
  mutate(year=as.numeric(as.character(year))) %>% 
  filter(Group==1, Type=="Treatment", year<=conyear) 
alder_growth <- portland_growth %>%  
  mutate(year=as.numeric(as.character(year))) %>% 
  filter(Group==1, Type=="Control: Alder", year<=conyear) 
everett_growth <- portland_growth %>%  
  mutate(year=as.numeric(as.character(year))) %>% 
  filter(Group==1, Type=="Control: Everett", year<=conyear) 

t.test(stark_growth$biz_growth,alder_growth$biz_growth)
t.test(stark_growth$retail_growth,alder_growth$retail_growth)
t.test(stark_growth$food_accom_growth,alder_growth$food_accom_growth)

t.test(stark_growth$biz_growth,everett_growth$biz_growth)
t.test(stark_growth$retail_growth,everett_growth$retail_growth)
t.test(stark_growth$food_accom_growth,everett_growth$food_accom_growth)

```

# plot trend
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}

stark_agg <- agg_trend_table(portland_corridor, group = 1)

stark_agg1 <- stark_agg %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS07/37,
                              Type == "Control: Alder"~ CNS07/26,
                              Type == "Control: Everett" ~ CNS07/27),
         CNS18_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS18/37,
                              Type == "Control: Alder"~ CNS18/26,
                              Type == "Control: Everett" ~ CNS18/27))


agg_retail_trend_plot <- agg_trend_plot(stark_agg, industry = "Retail", industry_code = "CNS07", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010)

agg_food_trend_plot <- agg_trend_plot(stark_agg, industry = "Food/Accommodataion",industry_code = "CNS18", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010)

plot_grid(agg_retail_trend_plot, agg_food_trend_plot)
```


## trend analysis - plot
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}

stark_agg <- agg_index_trend_table(portland_corridor, group = 1, construct_year = 2009)
stark_agg$Type <- as.character(stark_agg$Type)
portland <- portland_lehd %>% group_by(year) %>%
  summarise(CNS07 = sum(CNS07),
            CNS18 = sum(CNS18),
            business = CNS07 + CNS18) %>%
  mutate(CNS07_sd = CNS07/309.39,
         CNS18_sd = CNS18/301.37,
         business_sd = business/610.76,
         Type = "City") %>%
  select(Type, year, CNS07_sd, CNS18_sd, business_sd)
stark_agg <- rbind(as.data.frame(stark_agg), as.data.frame(portland))
stark_agg$Type <- as.factor(as.character(stark_agg$Type))

stark_agg_retail_plot <- agg_index_trend_plot(stark_agg, industry = "Retail", corridor_name = "Stark & Oak Ave.",industry_code = "CNS07_sd", construct_year = 2009, end_year = 2010)
stark_agg_food_plot <- agg_index_trend_plot(stark_agg, industry = "Food/Accommodations", corridor_name = "Stark & Oak Ave.",industry_code = "CNS18_sd", construct_year = 2009, end_year = 2010)

prow <- plot_grid(stark_agg_retail_plot + theme(legend.position="none"),
                  stark_agg_food_plot + theme(legend.position="none"), align = 'vh', hjust = -1, nrow = 1)
legend_b <- get_legend(stark_agg_retail_plot + theme(legend.position="bottom"))
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(3, .2))
```

## trend analysis - table
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}

# compute post change table compare to base year
post_change <- stark_agg %>% 
  filter (year %in% c(2009, 2010, 2011, 2012)) %>% 
  group_by(Type) %>% 
  mutate(retail_growth =(CNS07_sd/lag(CNS07_sd)-1)*100,
         food_accom_growth = (CNS18_sd/lag(CNS18_sd)-1)*100)
  
```


# model
```{r, echo=FALSE, results='asis'}

portland_corridor$Type <- ifelse(portland_corridor$Type=="Treatment: Stark & Oak", "Treatment", portland_corridor$Type)
portland_corridor$Type <- relevel(as.factor(portland_corridor$Type),ref = "Treatment")

#stark ave

stark_agg_did <- did_agg_analysis(portland_corridor, group = 1, endyear = 2010)
stargazer(stark_agg_did[[1]], stark_agg_did[[2]], stark_agg_did[[3]], 
          title = "Stark & Oak Ave. Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "text")

stark_agg_its <- agg_its_analysis(portland_corridor, group = 1, endyear = 2010)
stargazer(stark_agg_its[[1]], stark_agg_its[[2]], stark_agg_its[[3]], 
          title = "Stark & Oak Ave. Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "text")

```

# QCEW 

## trend analysis
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}

# source(here::here("Code/9-3_clean_portland_qcew.R"))
# cannot source by code, need manual source

stark_corridor1 <- stark_corridor_annual %>%
  mutate(Type = case_when(name=="Stark & Oak" ~ "Treatment",
                          name=="Alder"~ "Control:Alder",
                          name=="Everett"~ "Control:Everett"),
         Group=1,
         geometry="geometry") %>%
  select(Type, year, Group,geometry, busi_type, emp) %>%
  spread(busi_type,emp) %>% 
  rename(CNS07=Retail, CNS18=Food)

# number of blocks: Stark 37, alder 26, everett 27
stark_corridor1 <- stark_corridor1 %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment" ~ CNS07/37,
                              Type == "Control:Alder"~ CNS07/26,
                              Type == "Control:Everett" ~ CNS07/27),
         CNS18_pb = case_when(Type == "Treatment" ~ CNS18/37,
                              Type == "Control:Alder"~ CNS18/26,
                              Type == "Control:Everett" ~ CNS18/27))

stark_agg <- agg_index_trend_table(stark_corridor1, group = 1, construct_year = 2009)
stark_agg$Type <- as.character(stark_agg$Type)
portland <- portland_lehd %>% group_by(year) %>%
  summarise(CNS07 = sum(CNS07),
            CNS18 = sum(CNS18),
            business = CNS07 + CNS18) %>%
  mutate(CNS07_sd = CNS07/309.39,
         CNS18_sd = CNS18/301.37,
         business_sd = business/610.76,
         Type = "City") %>%
  select(Type, year, CNS07_sd, CNS18_sd, business_sd)
stark_agg <- rbind(as.data.frame(stark_agg), as.data.frame(portland))
stark_agg$Type <- as.factor(as.character(stark_agg$Type))

stark_agg_retail_plot <- agg_index_trend_plot(stark_agg, industry = "Retail", corridor_name = "Stark & Oak Ave.",industry_code = "CNS07_sd", construct_year = 2009, end_year = 2010)
stark_agg_food_plot <- agg_index_trend_plot(stark_agg, industry = "Food/Accommodations", corridor_name = "Stark & Oak Ave.",industry_code = "CNS18_sd", construct_year = 2009, end_year = 2010)

prow <- plot_grid(stark_agg_retail_plot + theme(legend.position="none"),
                  stark_agg_food_plot + theme(legend.position="none"), align = 'vh', hjust = -1, nrow = 1)
legend_b <- get_legend(stark_agg_retail_plot + theme(legend.position="bottom"))
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(3, .2))

# number of blocks: Stark 37, alder 26, everett 27
post_change <- stark_agg %>% 
  filter (year %in% c(2009, 2010, 2011, 2012)) %>% 
  group_by(Type) %>% 
  mutate(retail_growth =(CNS07_sd/lag(CNS07_sd)-1)*100,
         food_accom_growth = (CNS18_sd/lag(CNS18_sd)-1)*100)
```

# model
```{r, echo=FALSE, results='asis'}

stark_corridor1$Type <- relevel(as.factor(stark_corridor1$Type),ref = "Treatment")

#stark ave

stark_agg_did <- did_agg_analysis(stark_corridor1, group = 1, endyear = 2010)
stargazer(stark_agg_did[[1]], stark_agg_did[[2]], stark_agg_did[[3]], 
          title = "Stark & Oak Ave. Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "text")

stark_agg_its <- agg_its_analysis(stark_corridor1, group = 1, endyear = 2010)
stargazer(stark_agg_its[[1]], stark_agg_its[[2]], stark_agg_its[[3]], 
          title = "Stark & Oak Ave. Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "text")

```

# NETS analysis
## trend plot - industry type 1
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}
# one types of industry categories similar to LEHD
stark_nets_b <- pdx_stark_b %>% 
  group_by(name, type, buildstart, buildend, group, year, biz1) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% filter(biz1==c("Food", "Retail")) %>%
 as.data.frame(.) %>% select(-geometry)

pdx_nets1 <- pdx_nets1 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=1) %>% select(name:group, year:sales_pest) %>% as.data.frame()

stark_nets_b <- rbind(stark_nets_b, pdx_nets1) %>% mutate(geometry=0)

# employment plot
# abousolute employment
stark_nets1_emp <- stark_nets_b %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets1_emp $Type <- as.factor(stark_nets1_emp $Type)

nrow(portland_lehd %>% filter(year == 2009))
stark_nets1_emp1 <- stark_nets1_emp %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS07/37,
                              Type == "Control: Alder"~ CNS07/26,
                              Type == "Control: Everett" ~ CNS07/27,
                              Type == "City" ~ CNS07/7145),
         CNS18_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS18/37,
                              Type == "Control: Alder"~ CNS18/26,
                              Type == "Control: Everett" ~ CNS18/27,
                              Type == "City" ~ CNS18/7145))

stark_emp_retail_trend_plot <- trend_plot(filter(stark_nets1_emp, Type!="City"), industry = "Retail", industry_code = "CNS07", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Total")

stark_emp_food_trend_plot <- trend_plot(filter(stark_nets1_emp, Type!="City"), industry = "Food",industry_code = "CNS18", corridor_name = "Stark & Oak Street", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Total")

# A department store is opened with 1200 employment until 2003, and then the size shrink afterwards
# A restraunt is with 1000 eomploy until 1993, and then shrink afterwards

# employment per establishment
stark_nets1_emp_pest <- stark_nets_b %>% select(-sales, -n, -emp, -sales_pest) %>% spread(key = biz1, emp_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
stark_nets1_emp_pest $Type <- as.factor(as.character(stark_nets1_emp_pest $Type))

stark_emp_pest_retail_trend_plot <- trend_plot(stark_nets1_emp_pest, industry = "Retail", industry_code = "CNS07_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Per Establishment")

stark_emp_pest_food_trend_plot <- trend_plot(stark_nets1_emp_pest, industry = "Food",industry_code = "CNS18_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Per Establishment")

# indexed employment
stark_nets1_emp_idx <- agg_index_trend_table(stark_nets1_emp, group = 1, construct_year = 2009)
stark_nets1_emp_idx $Type <- as.factor(as.character(stark_nets1_emp_idx $Type))

stark_emp_retail_indexed_trend_plot <- trend_plot(stark_nets1_emp_idx, industry = "Retail", industry_code = "CNS07_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Indexed")

stark_emp_food_indexed_trend_plot <- trend_plot(stark_nets1_emp_idx, industry = "Food",industry_code = "CNS18_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Indexed")

prow <- plot_grid(stark_emp_retail_trend_plot + theme(legend.position="none"),
                  stark_emp_food_trend_plot + theme(legend.position="none"),
                  stark_emp_pest_retail_trend_plot + theme(legend.position="none"),
                  stark_emp_pest_food_trend_plot + theme(legend.position="none"),
                  stark_emp_retail_indexed_trend_plot + theme(legend.position="none"),
                  stark_emp_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(stark_emp_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(4, .2))

# sales plot
# abousolute sales
stark_nets1_sales <- stark_nets_b %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets1_sales $Type <- as.factor(stark_nets1_sales$Type)

stark_nets1_sales1 <- stark_nets1_sales %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS07/37,
                              Type == "Control: Alder"~ CNS07/26,
                              Type == "Control: Everett" ~ CNS07/27,
                              Type == "City" ~ CNS07/7145),
         CNS18_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS18/37,
                              Type == "Control: Alder"~ CNS18/26,
                              Type == "Control: Everett" ~ CNS18/27,
                              Type == "City" ~ CNS18/7145))

stark_sales_retail_trend_plot <- trend_plot(filter(stark_nets1_sales, Type!="City"), industry = "Retail", industry_code = "CNS07", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Total")

stark_sales_food_trend_plot <- trend_plot(filter(stark_nets1_sales, Type!="City"), industry = "Food",industry_code = "CNS18", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Total")


# sales per establishment
stark_nets1_sales_pest <- stark_nets_b %>% select(-sales, -n, -emp, -emp_pest) %>% spread(key = biz1, sales_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
stark_nets1_sales_pest $Type <- as.factor(as.character(stark_nets1_sales_pest $Type))

stark_sales_pest_retail_trend_plot <- trend_plot(stark_nets1_sales_pest, industry = "Retail", industry_code = "CNS07_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Per Establishment")

stark_sales_pest_food_trend_plot <- trend_plot(stark_nets1_sales_pest, industry = "Food",industry_code = "CNS18_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Per Establishment")

# indexed sales
stark_nets1_sales_idx <- agg_index_trend_table(stark_nets1_sales, group = 1, construct_year = 2009)
stark_nets1_sales_idx $Type <- as.factor(as.character(stark_nets1_sales_idx $Type))

stark_sales_retail_indexed_trend_plot <- trend_plot(stark_nets1_sales_idx, industry = "Retail", industry_code = "CNS07_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Indexed")

stark_sales_food_indexed_trend_plot <- trend_plot(stark_nets1_sales_idx, industry = "Food",industry_code = "CNS18_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Indexed")

prow <- plot_grid(stark_sales_retail_trend_plot + theme(legend.position="none"),
                  stark_sales_food_trend_plot + theme(legend.position="none"),
                  stark_sales_pest_retail_trend_plot + theme(legend.position="none"),
                  stark_sales_pest_food_trend_plot + theme(legend.position="none"),
                  stark_sales_retail_indexed_trend_plot + theme(legend.position="none"),
                  stark_sales_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(stark_sales_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(4, .2))


```

## trend plot - industry type 2
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}
# one types of industry categories similar to LEHD
stark_nets_bf <- pdx_stark_bf %>% 
  group_by(streetname, type, buildstart, buildend, group, year, biz2) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)
pdx_nets2 <- pdx_nets2 %>% 
  mutate(streetname="city", type="City", buildstart=0, buildend=0, group=1) %>% select(streetname:group, year:sales_pest)

stark_nets_bf <- rbind(stark_nets_bf, pdx_nets2) %>% mutate(geometry=0)

# employment plot
# abousolute employment
stark_nets2_emp <- stark_nets_bf %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets2_emp $Type <- as.factor(stark_nets2_emp $Type)

stark_nets2_emp1 <- stark_nets2_emp %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS07/37,
                              Type == "Control: Alder"~ CNS07/26,
                              Type == "Control: Everett" ~ CNS07/27,
                              Type == "City" ~ CNS07/7145),
         CNS18_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS18/37,
                              Type == "Control: Alder"~ CNS18/26,
                              Type == "Control: Everett" ~ CNS18/27,
                              Type == "City" ~ CNS18/7145))

stark_emp_retail_trend_plot <- trend_plot(filter(stark_nets2_emp, Type!="City"), industry = "Retail", industry_code = "CNS07", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Total")

stark_emp_food_trend_plot <- trend_plot(filter(stark_nets2_emp, Type!="City"), industry = "Food",industry_code = "CNS18", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Total")

# there is a communication equipment store close in 2011 with 130 employment

# employment per establishment
stark_nets2_emp_pest <- stark_nets_bf %>% select(-sales, -n, -emp, -sales_pest) %>% spread(key = biz2, emp_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
stark_nets2_emp_pest $Type <- as.factor(stark_nets2_emp_pest $Type)

stark_emp_pest_retail_trend_plot <- trend_plot(stark_nets2_emp_pest, industry = "Retail", industry_code = "CNS07_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Per Establishment")

stark_emp_pest_food_trend_plot <- trend_plot(stark_nets2_emp_pest, industry = "Food",industry_code = "CNS18_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Per Establishment")

# indexed employment
stark_nets2_emp_idx <- agg_index_trend_table(stark_nets2_emp, group = 1, construct_year = 2009)
stark_nets2_emp_idx $Type <- as.factor(stark_nets2_emp_idx $Type)

stark_emp_retail_indexed_trend_plot <- trend_plot(stark_nets2_emp_idx, industry = "Retail", industry_code = "CNS07_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Indexed")

stark_emp_food_indexed_trend_plot <- trend_plot(stark_nets2_emp_idx, industry = "Food",industry_code = "CNS18_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Employment", index = "Indexed")

prow <- plot_grid(stark_emp_retail_trend_plot + theme(legend.position="none"),
                  stark_emp_food_trend_plot + theme(legend.position="none"),
                  stark_emp_pest_retail_trend_plot + theme(legend.position="none"),
                  stark_emp_pest_food_trend_plot + theme(legend.position="none"),
                  stark_emp_retail_indexed_trend_plot + theme(legend.position="none"),
                  stark_emp_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(stark_emp_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(2, .2))

# sales plot
# abousolute sales
stark_nets2_sales <- stark_nets_bf %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets2_sales $Type <- as.factor(stark_nets2_sales$Type)

stark_nets2_sales1 <- stark_nets2_sales %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS07/37,
                              Type == "Control: Alder"~ CNS07/26,
                              Type == "Control: Everett" ~ CNS07/27,
                              Type == "City" ~ CNS07/7145),
         CNS18_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS18/37,
                              Type == "Control: Alder"~ CNS18/26,
                              Type == "Control: Everett" ~ CNS18/27,
                              Type == "City" ~ CNS18/7145))

stark_nets2_sales1 <- stark_nets2_sales %>% 
  mutate(CNS07_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS07/37,
                              Type == "Control: Alder"~ CNS07/26,
                              Type == "Control: Everett" ~ CNS07/27,
                              Type == "City" ~ CNS07/7145),
         CNS18_pb = case_when(Type == "Treatment: Stark & Oak" ~ CNS18/37,
                              Type == "Control: Alder"~ CNS18/26,
                              Type == "Control: Everett" ~ CNS18/27,
                              Type == "City" ~ CNS18/7145))

stark_sales_retail_trend_plot <- trend_plot(filter(stark_nets2_sales, Type!="City"), industry = "Retail", industry_code = "CNS07", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Total")

stark_sales_food_trend_plot <- trend_plot(filter(stark_nets2_sales, Type!="City"), industry = "Food",industry_code = "CNS18", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Total")


# sales per establishment
stark_nets2_sales_pest <- stark_nets_bf %>% select(-sales, -n, -emp, -emp_pest) %>% spread(key = biz2, sales_pest) %>% 
  rename(CNS07_pest = Retail, CNS18_pest = Food, Group=group, Type= type)
stark_nets2_sales_pest $Type <- as.factor(stark_nets2_sales_pest $Type)

stark_sales_pest_retail_trend_plot <- trend_plot(stark_nets2_sales_pest, industry = "Retail", industry_code = "CNS07_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Per Establishment")

stark_sales_pest_food_trend_plot <- trend_plot(stark_nets2_sales_pest, industry = "Food",industry_code = "CNS18_pest", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Per Establishment")

# indexed sales
stark_nets2_sales_idx <- agg_index_trend_table(stark_nets2_sales, group = 1, construct_year = 2009)
stark_nets2_sales_idx $Type <- as.factor(stark_nets2_sales_idx $Type)

stark_sales_retail_indexed_trend_plot <- trend_plot(stark_nets2_sales_idx, industry = "Retail", industry_code = "CNS07_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Indexed")

stark_sales_food_indexed_trend_plot <- trend_plot(stark_nets2_sales_idx, industry = "Food",industry_code = "CNS18_sd", corridor_name = "Stark & Oak Avenue", construct_year = 2009, end_year = 2010, y_lable = "Sales", index = "Indexed")

prow <- plot_grid(stark_sales_retail_trend_plot + theme(legend.position="none"),
                  stark_sales_food_trend_plot + theme(legend.position="none"),
                  stark_sales_pest_retail_trend_plot + theme(legend.position="none"),
                  stark_sales_pest_food_trend_plot + theme(legend.position="none"),
                  stark_sales_retail_indexed_trend_plot + theme(legend.position="none"),
                  stark_sales_food_indexed_trend_plot + theme(legend.position="none"), 
           align = 'vh', hjust = -1, nrow = 3)

legend_b <- get_legend(stark_sales_retail_indexed_trend_plot + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(4, .2))


```


## trend analysis - table
```{r echo=FALSE, fig.asp=0.5, fig.width=9.5, message=FALSE, warning=FALSE}

# compute post change table compare to base year
stark_nets1_emp %>% 
  filter (year %in% c(2009, 2010, 2011, 2012)) %>% 
  group_by(Type) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)

stark_nets1_sales %>% 
  filter (year %in% c(2009, 2010, 2011, 2012)) %>% 
  group_by(Type) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)


stark_nets2_emp %>% 
  filter (year %in% c(2009, 2010, 2011, 2012)) %>% 
  group_by(Type) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)

stark_nets2_sales %>% 
  filter (year %in% c(2009, 2010, 2011, 2012)) %>% 
  group_by(Type) %>% 
  mutate(retail_growth =(CNS07/lag(CNS07)-1)*100,
         food_accom_growth = (CNS18/lag(CNS18)-1)*100)
  
```

# model
```{r, echo=FALSE, results='asis'}
# DID
#employment
stark_nets1_emp$Type <- relevel(stark_nets1_emp$Type,ref = "Treatment: Stark & Oak")
stark_nets2_emp$Type <- relevel(stark_nets2_emp$Type,ref = "Treatment: Stark & Oak")

stark_nets1_emp_did <- did_agg_analysis(filter(stark_nets1_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stark_nets2_emp_did <- did_agg_analysis(filter(stark_nets2_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stargazer(stark_nets1_emp_did[[1]], stark_nets2_emp_did[[1]], stark_nets1_emp_did[[2]], stark_nets2_emp_did[[2]],
          stark_nets1_emp_did[[3]], stark_nets2_emp_did[[3]],
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business"), model.numbers = F)

# sales
stark_nets1_sales$Type <- relevel(stark_nets1_sales$Type,ref = "Treatment: Stark & Oak")
stark_nets2_sales$Type <- relevel(stark_nets2_sales$Type,ref = "Treatment: Stark & Oak")

stark_nets1_sales_did <- did_agg_analysis(filter(stark_nets1_sales, Type!="City" & year>2003), group = 1, endyear = 2010)
stark_nets2_sales_did <- did_agg_analysis(filter(stark_nets2_sales, Type!="City" & year>2003), group = 1, endyear = 2010)
stargazer(stark_nets1_sales_did[[1]], stark_nets2_sales_did[[1]], stark_nets1_sales_did[[2]], stark_nets2_sales_did[[2]], 
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

# show only Type 2 results
stargazer(stark_nets2_emp_did[[1]], stark_nets2_emp_did[[2]], stark_nets2_emp_did[[2]],
          stark_nets2_sales_did[[1]],  stark_nets2_sales_did[[2]], stark_nets2_sales_did[[3]],
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "text", dep.var.labels = c("Employment","Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)
# ITS
stark_nets1_emp_its <- agg_its_analysis(filter(stark_nets1_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stark_nets2_emp_its <- agg_its_analysis(filter(stark_nets2_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stargazer(stark_nets1_emp_its[[1]], stark_nets2_emp_its[[1]], stark_nets1_emp_its[[2]], stark_nets2_emp_its[[2]], 
          stark_nets1_emp_its[[3]], stark_nets2_emp_its[[3]],
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2",  "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business Emp."), model.numbers = F)


stark_nets1_sales_its <- agg_its_analysis(stark_nets1_sales, group = 1, endyear = 2010)
stark_nets2_sales_its <- agg_its_analysis(stark_nets2_sales, group = 1, endyear = 2010)
stargazer(stark_nets1_sales_its[[1]], stark_nets2_sales_its[[1]], stark_nets1_sales_its[[2]], stark_nets2_sales_its[[2]], 
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)


```

