---
title: "memphis_models"
author: "Wei Shi"
date: "August 20, 2018"
output: html_document
---

```{r}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, dplyr, dbplyr, stargazer,cowplot)

#query the corridors from bike_lanes
user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)

source(here::here("Code/corridor_comparison_functions.R"))

memphis_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns18 as cns18, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, b.name as Name, 
b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM memphis_lehd a, memhpis_corridors b
WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

memphis_corridor$Type <- ifelse(is.na(memphis_corridor$buildstart),"Control", "Treatment")
memphis_corridor[memphis_corridor$name =="Central Avenue",]$Type <- "Control: Central"
memphis_corridor[memphis_corridor$name=="Cooper Street",]$Type <- "Control: Cooper"
memphis_corridor[memphis_corridor$name=="Highland Street",]$Type <- "Control: Highland"
memphis_corridor[memphis_corridor$name=="Jackson Avenue",]$Type <- "Control: Jackson"
memphis_corridor[memphis_corridor$name=="Union Avenue",]$Type <- "Control: Union"
memphis_corridor$Type <- as.factor(memphis_corridor$Type)

memphis_corridor <- memphis_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, Group = corridor_group,
         BuildStart = buildstart, BuildEnd = buildend, Name = name)


memphis_sales <- tbl(con, "memphis_sales_tax") %>% 
  collect()%>% 
  mutate(year = format(pctym, "%Y"),
         Type = paste(street_type, district_name, sep=": ")) %>% 
  group_by(year,district_name, street_type, street_group, Type) %>% 
  summarise(business = mean(businesses),
            gross_sales = sum(gross_sales))
```

# LEHD data
```{r, echo=FALSE, results='asis'}
# exclude Jackson corridor which is not comparable to treatment corridor
memphis_corridor <- memphis_corridor[memphis_corridor$Name!="Jackson Avenue",]
memphis_corridor$Type <- relevel(memphis_corridor$Type,ref = "Treatment")

#madison ave

madison_agg_did <- did_agg_analysis(memphis_corridor, group = 1, endyear = 2011)
stargazer(madison_agg_did[[1]], madison_agg_did[[2]], madison_agg_did[[3]], 
          title = "Madison Ave. Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "html")

madison_agg_its <- agg_its_analysis(memphis_corridor, group = 1, endyear = 2011)
stargazer(madison_agg_its[[1]], madison_agg_its[[2]], madison_agg_its[[3]], 
          title = "Madison Ave. Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "html")


#broad ave

broad_agg_did <- did_agg_analysis(memphis_corridor, group = 2, endyear = 2010)
stargazer(broad_agg_did[[1]], broad_agg_did[[2]], broad_agg_did[[3]], 
          title = "Broad Ave. Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "html")

broad_agg_its <- agg_its_analysis(memphis_corridor, group = 2, endyear = 2010)
stargazer(broad_agg_its[[1]], broad_agg_its[[2]], broad_agg_its[[3]], 
          title = "Broad Ave. Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail Emp.", "Accomodations Emp.", "'Business' Emp."), type = "html")


```


# Sales
```{r, echo=FALSE, results='asis'}

#madison ave
madison_sales <- memphis_sales %>% 
  filter(street_group == 1) %>% 
  mutate(prepost = ifelse(as.numeric(year)>2011,1,0),
         ts_year = as.numeric(year)-2006)

madison_sales <- madison_sales[madison_sales$Type!="Control: Jackson Ave",]
madison_sales$Type <- factor(madison_sales$Type)
madison_sales$Type <- relevel(madison_sales$Type, ref = 4)


madison_agg_did_sales <- lm(gross_sales ~ Type + prepost + Type*prepost, data=madison_sales)
madison_agg_did_business <- lm(business ~ Type + prepost + Type*prepost, data=madison_sales)
stargazer(madison_agg_did_sales,madison_agg_did_business, title = "Madison Ave. Corridor Difference-in-Difference Estimates", type = "html")

madison_agg_its_sales <- lm(gross_sales ~ ts_year + prepost + ts_year*prepost, data=filter(madison_sales, street_type == "Treatment"))
madison_agg_its_business <- lm(business ~ ts_year + prepost + ts_year*prepost, data=filter(madison_sales, street_type == "Treatment"))
stargazer(madison_agg_its_sales,madison_agg_its_business, title = "Madison Ave. Corridor Time Series Estimates", type = "html")



#broad ave
broad_sales <- memphis_sales %>% 
  filter(street_group == 2) %>% 
  mutate(prepost = ifelse(as.numeric(year)>2010,1,0),
         ts_year = as.numeric(year)-2006)

broad_sales$Type <- factor(broad_sales$Type)
broad_sales$Type <- relevel(broad_sales$Type, ref = 3)

broad_agg_did_sales <- lm(gross_sales ~ Type + prepost + Type*prepost, data=broad_sales)
broad_agg_did_business <- lm(business ~ Type + prepost + Type*prepost, data=broad_sales)
stargazer(broad_agg_did_sales, broad_agg_did_business, title = "Broad Ave. Corridor Difference-in-Difference Estimates", type = "html")

broad_agg_its_sales <- lm(gross_sales ~ ts_year + prepost + ts_year*prepost, data=filter(broad_sales, street_type == "Treatment"))
broad_agg_its_business <- lm(business ~ ts_year + prepost + ts_year*prepost, data=filter(broad_sales, street_type == "Treatment"))
stargazer(broad_agg_its_sales, broad_agg_its_business, title = "Broad Ave. Corridor Time Series Estimates", type = "html")


```