---
title: "minn_model_outpus"
author: "Wei Shi"
date: "February 11, 2019"
output: html_document
---

# load data
```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, tidyverse, dbplyr, stargazer,cowplot, lubridate, gridExtra,data.table)

user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)


source(here::here("Code/corridor_comparison_functions.R"))

minn_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, a.ce01 as ce01, a.ce02 as ce02, a.ce03 as ce03, a.cr01 as cr01,a.cr02 as cr02, a.cr03 as cr03, a.cr04 as cr04, a.cr05 as cr05, a.cr07 as cr07, a.cs02 as cs02, a.cd01 as cd01, a.cd02 as cd02, a.cd02 as cd03, a.cd04 as cd04, b.name as Name, b.type as Type, b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM minneapolis_lehd a, minneapolis_corridors b
WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

minn_corridor[minn_corridor$name=="Central Ave (improvement)",]$type <- "Treatment: Central"
minn_corridor[minn_corridor$name =="University Ave NE (control)",]$type <- "Control: University"
minn_corridor[minn_corridor$name=="Franklin Ave (improvement)",]$type <- "Treatment: Franklin"
minn_corridor[minn_corridor$name=="Franklin Ave (control)",]$type <- "Control: Franklin"

minn_corridor <- minn_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08,CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, Group = corridor_group, BuildStart = buildstart, BuildEnd = buildend, Name = name)

minn_lehd <- st_read(dsn = con, "minneapolis_lehd") %>% as.data.frame()

minn_lehd <- minn_lehd %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08,CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19)


minn_emp_ratio <- employ_ratio_test(minn_corridor)

minn_growth <- growth_rate(minn_corridor)



# load nets
minn_nets <- st_read(dsn = con, query = "select * FROM nets") %>% filter(city =="MINNEAPOLIS")

minn_blocks <- left_join(as.data.frame(minn_corridor), unique(minn_lehd[,c(1,56)]), by =c("geoid" = "geoid10")) %>% 
  mutate(geometry.x=NULL, geometry=geometry.y, geometry.y=NULL) %>% st_sf

minn_nets_b <- st_join(minn_nets, unique(minn_blocks[,c(26:30,32)]) %>% st_sf, join=st_intersects, left=F)  
names(minn_nets_b)  <- tolower(names(minn_nets_b))

# minn_nets_bf <- st_read(dsn = con, query = "select * FROM nets a, minneapolis_corridors b WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

minn_c <-  st_read(dsn = con, "minneapolis_corridors")
minn_nets_bf <- st_intersection(minn_nets, st_buffer(minn_c, 20)) %>% select(-id, -descriptio)

minn_nets_bf[minn_nets_bf$name=="Central Ave (improvement)",]$type <- "Treatment: Central"
minn_nets_bf[minn_nets_bf$name =="University Ave NE (control)",]$type <- "Control: University"
minn_nets_bf[minn_nets_bf$name=="Franklin Ave (improvement)",]$type <- "Treatment: Franklin"
minn_nets_bf[minn_nets_bf$name=="Franklin Ave (control)",]$type <- "Control: Franklin"

minn_central_b <- minn_nets_b %>% 
  filter(group==3) %>% 
  gather(key, value, -c(1:10,89:97)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
minn_central_bf <- minn_nets_bf %>% 
  filter(group==3) %>% 
  gather(key, value, -c(1:10,89:99)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
minn_frkl_b <- minn_nets_b %>% 
  filter(group==2) %>% 
  gather(key, value, -c(1:10,89:97)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
minn_frkl_bf <- minn_nets_bf %>% 
  filter(group==2) %>% 
  gather(key, value, -c(1:10,89:99)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 

nets <- setDT(minn_nets)
nets <- setkey(nets, dunsnumber)
nets_long <- melt(nets, id.vars = c("dunsnumber", "city"),
                  measure.vars = 11:88,
                  variable.factor = TRUE)

minn_nets_a <- nets_long %>% 
  separate(variable, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))

minn_nets1 <- minn_nets_a %>% 
  group_by(year, biz1) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)

minn_nets2 <- minn_nets_a %>% 
  group_by(year, biz2) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)


dbDisconnect(con)

```

# prep data
```{r}
central_nets_b <- minn_central_b %>% 
  group_by(name, type, buildstart, buildend, group, year, biz1) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% filter(biz1==c("Food", "Retail")) %>%
 as.data.frame(.) %>% select(-geometry)

minn_nets1 <- minn_nets1 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=3) %>% select(name:group, year:sales_pest) %>% as.data.frame()

central_nets_b <- rbind(central_nets_b, minn_nets1) %>% mutate(geometry=0)

# employment plot
# abousolute employment
central_nets1_emp <- central_nets_b %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, emp) %>%
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
central_nets1_emp $Type <- as.factor(central_nets1_emp $Type)

central_nets1_sales <- central_nets_b %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
central_nets1_sales $Type <- as.factor(central_nets1_sales$Type)

# one types of industry categories only with block face establishments
central_nets_bf <- minn_central_bf %>% 
  mutate(buildstart = as.numeric(buildstart), buildend=as.numeric(buildend)) %>% 
  mutate(buildstart = ifelse(is.na(buildstart), 0, buildstart),
         buildend = ifelse(is.na(buildend), 0, buildend)) %>% 
  group_by(name, type, buildstart, buildend, group, year, biz2) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)
  
minn_nets2 <- minn_nets2 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=3) %>% select(name:group, year:sales_pest)

central_nets_bf <- rbind(central_nets_bf, minn_nets2) %>% mutate(geometry=0)

# employment plot
# abousolute employment
central_nets2_emp <- central_nets_bf %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
central_nets2_emp $Type <- as.factor(central_nets2_emp $Type)

central_nets2_sales <- central_nets_bf %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
central_nets2_sales $Type <- as.factor(central_nets2_sales$Type)
```


# DID
```{r, echo=FALSE, results='asis'}
# DID
#employment
central_nets1_emp$Type <- relevel(central_nets1_emp$Type,ref = "Treatment: Central")
central_nets2_emp$Type <- relevel(central_nets2_emp$Type,ref = "Treatment: Central")

central_nets1_emp_did <- did_agg_analysis(filter(central_nets1_emp, Type!="City" & year>2005), group = 3, endyear = 2013)
central_nets2_emp_did <- did_agg_analysis(filter(central_nets2_emp, Type!="City" & year>2005), group = 3, endyear = 2013)
stargazer(central_nets1_emp_did[[1]], central_nets2_emp_did[[1]], central_nets1_emp_did[[2]], central_nets2_emp_did[[2]],
          central_nets1_emp_did[[3]], central_nets2_emp_did[[3]],
          title = "Central Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business"), model.numbers = F)

# sales
central_nets1_sales$Type <- relevel(central_nets1_sales$Type,ref = "Treatment: Central")
central_nets2_sales$Type <- relevel(central_nets2_sales$Type,ref = "Treatment: Central")

central_nets1_sales_did <- did_agg_analysis(filter(central_nets1_sales, Type!="City" & year>2005), group = 3, endyear = 2013)
central_nets2_sales_did <- did_agg_analysis(filter(central_nets2_sales, Type!="City" & year>2005), group = 3, endyear = 2013)
stargazer(central_nets1_sales_did[[1]], central_nets2_sales_did[[1]], central_nets1_sales_did[[2]], central_nets2_sales_did[[2]], 
          title = "Central Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

stargazer(central_nets2_emp_did[[1]], central_nets2_emp_did[[2]], central_nets2_emp_did[[3]],
          central_nets2_sales_did[[1]],  central_nets2_sales_did[[2]], central_nets2_sales_did[[3]],
          title = "Central Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)
```

# ITS
```{r,echo=FALSE, results='asis'}
central_nets1_emp <- central_nets1_emp %>% mutate(Type = ifelse(Type=="Treatment: Central", "Treatment", Type))
central_nets2_emp <- central_nets2_emp %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Central", "Treatment", Type))
central_nets1_sales <- central_nets1_sales %>% 
  mutate(Type = ifelse(Type=="Treatment: Central", "Treatment", Type))
central_nets2_sales <- central_nets2_sales %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Central", "Treatment", Type))

central_nets1_emp_its <- agg_its_analysis(filter(central_nets1_emp, Type!="City" & year>2005), group = 3, endyear = 2013)
central_nets2_emp_its <- agg_its_analysis(filter(central_nets2_emp, Type!="City" & year>2005), group = 3, endyear = 2013)
stargazer(central_nets1_emp_its[[1]], central_nets2_emp_its[[1]], central_nets1_emp_its[[2]], central_nets2_emp_its[[2]], 
          central_nets1_emp_its[[3]], central_nets2_emp_its[[3]],
          title = "Central Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2",  "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business Emp."), model.numbers = F)


central_nets1_sales_its <- agg_its_analysis(filter(central_nets1_sales, Type!="City" & year>2005), group = 3, endyear = 2013)
central_nets2_sales_its <- agg_its_analysis(filter(central_nets2_sales, Type!="City" & year>2005), group = 3, endyear = 2013)
stargazer(central_nets1_sales_its[[1]], central_nets2_sales_its[[1]], central_nets1_sales_its[[2]], central_nets2_sales_its[[2]], 
          title = "Central Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)


stargazer(central_nets2_emp_its[[1]], central_nets2_emp_its[[2]], central_nets2_emp_its[[3]],
          central_nets2_sales_its[[1]],  central_nets2_sales_its[[2]], central_nets2_sales_its[[3]],
          title = "Central Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)
```

# prep data: franklin
```{r}
frkl_nets_b <- minn_frkl_b %>% 
  group_by(name, type, buildstart, buildend, group, year, biz1) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% filter(biz1==c("Food", "Retail")) %>%
 as.data.frame(.) %>% select(-geometry)

minn_nets1 <- minn_nets1 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=2) %>% select(name:group, year:sales_pest) %>% as.data.frame()

frkl_nets_b <- rbind(frkl_nets_b, minn_nets1) %>% mutate(geometry=0)

frkl_nets1_emp <- frkl_nets_b %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, emp) %>%
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
frkl_nets1_emp $Type <- as.factor(frkl_nets1_emp $Type)

frkl_nets1_sales <- frkl_nets_b %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
frkl_nets1_sales $Type <- as.factor(frkl_nets1_sales$Type)

frkl_nets_bf <- minn_frkl_bf %>% 
  mutate(buildstart = as.numeric(buildstart), buildend=as.numeric(buildend)) %>% 
  mutate(buildstart = ifelse(is.na(buildstart), 0, buildstart),
         buildend = ifelse(is.na(buildend), 0, buildend)) %>% 
  group_by(name, type, buildstart, buildend, group, year, biz2) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)
  
minn_nets2 <- minn_nets2 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=2) %>% select(name:group, year:sales_pest)

frkl_nets_bf <- rbind(frkl_nets_bf, minn_nets2) %>% mutate(geometry=0)

frkl_nets2_emp <- frkl_nets_bf %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
frkl_nets2_emp $Type <- as.factor(frkl_nets2_emp $Type)

frkl_nets2_sales <- frkl_nets_bf %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
frkl_nets2_sales $Type <- as.factor(frkl_nets2_sales$Type)
```

# models
```{r,echo=FALSE, results='asis'}
# DID
#employment
frkl_nets1_emp$Type <- relevel(frkl_nets1_emp$Type,ref = "Treatment: Franklin")
frkl_nets2_emp$Type <- relevel(frkl_nets2_emp$Type,ref = "Treatment: Franklin")

frkl_nets1_emp_did <- did_agg_analysis(filter(frkl_nets1_emp, Type!="City" & year>2005), group = 2, endyear = 2012)
frkl_nets2_emp_did <- did_agg_analysis(filter(frkl_nets2_emp, Type!="City" & year>2005), group = 2, endyear = 2012)
stargazer(frkl_nets1_emp_did[[1]], frkl_nets2_emp_did[[1]], frkl_nets1_emp_did[[2]], frkl_nets2_emp_did[[2]],
          frkl_nets1_emp_did[[3]], frkl_nets2_emp_did[[3]],
          title = "Franklin Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business"), model.numbers = F)

# sales
frkl_nets1_sales$Type <- relevel(frkl_nets1_sales$Type,ref = "Treatment: Franklin")
frkl_nets2_sales$Type <- relevel(frkl_nets2_sales$Type,ref = "Treatment: Franklin")

frkl_nets1_sales_did <- did_agg_analysis(filter(frkl_nets1_sales, Type!="City" & year>2005), group = 2, endyear = 2012)
frkl_nets2_sales_did <- did_agg_analysis(filter(frkl_nets2_sales, Type!="City" & year>2005), group = 2, endyear = 2012)
stargazer(frkl_nets1_sales_did[[1]], frkl_nets2_sales_did[[1]], frkl_nets1_sales_did[[2]], frkl_nets2_sales_did[[2]], 
          title = "Franklin Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

# show only Type 2 results
stargazer(frkl_nets2_emp_did[[1]], frkl_nets2_emp_did[[2]], frkl_nets2_emp_did[[3]],
          frkl_nets2_sales_did[[1]],  frkl_nets2_sales_did[[2]], frkl_nets2_sales_did[[3]],
          title = "Franklin Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

# ITS
frkl_nets1_emp <- frkl_nets1_emp %>% 
  mutate(Type = ifelse(Type=="Treatment: Franklin", "Treatment", as.character(Type)))
frkl_nets2_emp <- frkl_nets2_emp %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Franklin", "Treatment", as.character(Type)))
frkl_nets1_sales <- frkl_nets1_sales %>% 
  mutate(Type = ifelse(Type=="Treatment: Franklin", "Treatment", as.character(Type)))
frkl_nets2_sales <- frkl_nets2_sales %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Franklin", "Treatment", as.character(Type)))

frkl_nets1_emp_its <- agg_its_analysis(filter(frkl_nets1_emp, Type!="City" & year>2005), group = 2, endyear = 2012)
frkl_nets2_emp_its <- agg_its_analysis(filter(frkl_nets2_emp, Type!="City" & year>2005), group = 2, endyear = 2012)
stargazer(frkl_nets1_emp_its[[1]], frkl_nets2_emp_its[[1]], frkl_nets1_emp_its[[2]], frkl_nets2_emp_its[[2]], 
          frkl_nets1_emp_its[[3]], frkl_nets2_emp_its[[3]],
          title = "Franklin Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2",  "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business Emp."), model.numbers = F)


frkl_nets1_sales_its <- agg_its_analysis(filter(frkl_nets1_sales, Type!="City" & year>2005), group = 2, endyear = 2012)
frkl_nets2_sales_its <- agg_its_analysis(filter(frkl_nets2_sales, Type!="City" & year>2005), group = 2, endyear = 2012)
stargazer(frkl_nets1_sales_its[[1]], frkl_nets2_sales_its[[1]], frkl_nets1_sales_its[[2]], frkl_nets2_sales_its[[2]], 
          title = "Franklin Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)


stargazer(frkl_nets2_emp_its[[1]], frkl_nets2_emp_its[[2]], frkl_nets2_emp_its[[3]],
          frkl_nets2_sales_its[[1]],  frkl_nets2_sales_its[[2]], frkl_nets2_sales_its[[3]],
          title = "Franklin Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)
```

