---
title: "pdx_models"
author: "Wei Shi"
date: "February 25, 2019"
output: html_document
---
## load data

```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, tidyverse, dbplyr, stargazer,cowplot, lubridate, gridExtra,data.table)

#query the corridors from bike_lanes
user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)

source(here::here("Code/corridor_comparison_functions.R"))

portland_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, a.ce01 as ce01, a.ce02 as ce02, a.ce03 as ce03, a.cr01 as cr01,a.cr02 as cr02, a.cr03 as cr03, a.cr04 as cr04, a.cr05 as cr05, a.cr07 as cr07, a.cs02 as cs02, a.cd01 as cd01, a.cd02 as cd02, a.cd02 as cd03, a.cd04 as cd04, b.streetname as Name, b.type as Type, b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM portland_lehd a, portland_corridors b
WHERE ST_Intersects(ST_Buffer(b.geometry, 20), a.geometry);")

portland_corridor[portland_corridor$name =="STARK_OAK",]$type <- "Treatment: Stark & Oak"
portland_corridor[portland_corridor$name =="EVERETT",]$type <- "Control: Everett"
portland_corridor[portland_corridor$name=="ALDER",]$type <- "Control: Alder"
portland_corridor$type <- as.factor(portland_corridor$type)

portland_corridor <- portland_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04,
         Group=corridor_group, BuildStart = buildstart, BuildEnd = buildend, Name = name, Type=type)

portland_lehd <- st_read(dsn = con, query = "SELECT * FROM portland_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, CE01=ce01, CE02=ce02, 
         CE03=ce03, CR01=cr01, CR02=cr02, CR03=cr03, CR04=cr04, CR05=cr05, CR07=cr07, CS02=cs02, 
         CD01=cd01, CD02=cd02, CD03=cd03, CD04=cd04)

portland_emp_ratio <- employ_ratio_test(portland_corridor)

portland_growth <- growth_rate(portland_corridor)

# load nets
pdx_nets <- st_read(dsn = con, query = "select * FROM nets") %>% filter(city =="PORTLAND")

pdx_blocks <- left_join(as.data.frame(portland_corridor), unique(portland_lehd[,c(1,56)]), by =c("geoid" = "geoid10")) %>% 
  mutate(geometry.x=NULL, geometry=geometry.y, geometry.y=NULL) %>% st_sf

pdx_nets_b <- st_join(pdx_nets, unique(pdx_blocks[,c(26:30,32)]) %>% st_sf, join=st_intersects, left=F)  
names(pdx_nets_b)  <- tolower(names(pdx_nets_b))

pdx_nets_bf <- st_read(dsn = con, query = "select * FROM nets a, portland_corridors b
WHERE ST_Intersects(ST_Buffer(b.geometry, 20), a.geometry);")

pdx_nets_bf[pdx_nets_bf$streetname=="STARK_OAK",]$type <- "Treatment: Stark & Oak"
pdx_nets_bf[pdx_nets_bf$streetname =="EVERETT",]$type <- "Control: Everett"
pdx_nets_bf[pdx_nets_bf$streetname=="ALDER",]$type <- "Control: Alder"

 pdx_stark_b <- pdx_nets_b %>% 
  filter(group==1) %>% 
  gather(key, value, -c(1:10,89:97)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))
 
 pdx_stark_bf <- pdx_nets_bf %>% 
  filter(group==1) %>% 
  gather(key, value, -c(1:10,89:99)) %>% 
  separate(key, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year))) %>% 
   select(-c("objectid", shape_leng))
 

nets <- setDT(pdx_nets)
nets <- setkey(nets, dunsnumber)
nets_long <- melt(nets, id.vars = c("dunsnumber", "city"),
                  measure.vars = 11:88,
                  variable.factor = TRUE)

pdx_nets_a <- nets_long %>% 
  separate(variable, c("retail", "year"), sep=-2) %>% 
  spread(retail, value) %>% 
  mutate(biz1 = case_when(substr(naics,1,3) %in% c(441:454) ~ "Retail",
                               substr(naics,1,3) %in% c(722) ~ "Food"),
         biz2 = case_when((substr(naics,1,3) %in% c(443,445,446,448,451,452,453)|substr(naics,1,4) %in% c(8121,8123,8129)) ~ "Retail",
                               substr(naics,1,4) %in% c(7224,7225) ~ "Food"),
         year = ifelse(as.numeric(year)<16, paste0("20",year), paste0("19",year)))

pdx_nets1 <- pdx_nets_a %>% 
  group_by(year, biz1) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)

pdx_nets2 <- pdx_nets_a %>% 
  group_by(year, biz2) %>% 
  summarise(emp = sum(emp, na.rm = T), sales= sum(sales, na.rm = T), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)


dbDisconnect(con)

```

# NETS analysis
## trend plot - industry type 1
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}
# one types of industry categories similar to LEHD
stark_nets_b <- pdx_stark_b %>% 
  group_by(name, type, buildstart, buildend, group, year, biz1) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% filter(biz1==c("Food", "Retail")) %>%
 as.data.frame(.) %>% select(-geometry)

pdx_nets1 <- pdx_nets1 %>% 
  mutate(name="city", type="City", buildstart=0, buildend=0, group=1) %>% select(name:group, year:sales_pest) %>% as.data.frame()

stark_nets_b <- rbind(stark_nets_b, pdx_nets1) %>% mutate(geometry=0)

# employment plot
# abousolute employment
stark_nets1_emp <- stark_nets_b %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets1_emp $Type <- as.factor(stark_nets1_emp $Type)

# sales plot
# abousolute sales
stark_nets1_sales <- stark_nets_b %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz1, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets1_sales $Type <- as.factor(stark_nets1_sales$Type)

# indexed sales
stark_nets1_sales_idx <- agg_index_trend_table(stark_nets1_sales, group = 1, construct_year = 2009)
stark_nets1_sales_idx $Type <- as.factor(as.character(stark_nets1_sales_idx $Type))



```

## trend plot - industry type 2
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=1.3}
# one types of industry categories similar to LEHD
stark_nets_bf <- pdx_stark_bf %>% 
  group_by(streetname, type, buildstart, buildend, group, year, biz2) %>% 
  summarise(emp = sum(emp), sales= sum(sales), n=n(),
            emp_pest = emp/n, sales_pest = sales/n) %>% drop_na(.)
pdx_nets2 <- pdx_nets2 %>% 
  mutate(streetname="city", type="City", buildstart=0, buildend=0, group=1) %>% select(streetname:group, year:sales_pest)

stark_nets_bf <- rbind(stark_nets_bf, pdx_nets2) %>% mutate(geometry=0)

# employment plot
# abousolute employment
stark_nets2_emp <- stark_nets_bf %>% select(-sales, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, emp) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets2_emp $Type <- as.factor(stark_nets2_emp $Type)

# indexed employment
stark_nets2_emp_idx <- agg_index_trend_table(stark_nets2_emp, group = 1, construct_year = 2009)
stark_nets2_emp_idx $Type <- as.factor(stark_nets2_emp_idx $Type)



# sales plot
# abousolute sales
stark_nets2_sales <- stark_nets_bf %>% select(-emp, -n, -emp_pest, -sales_pest) %>% spread(key = biz2, sales) %>% 
  rename(CNS07 = Retail, CNS18 = Food, Group=group, Type= type)
stark_nets2_sales $Type <- as.factor(stark_nets2_sales$Type)

# indexed sales
stark_nets2_sales_idx <- agg_index_trend_table(stark_nets2_sales, group = 1, construct_year = 2009)
stark_nets2_sales_idx $Type <- as.factor(stark_nets2_sales_idx $Type)


```


# model
```{r, echo=FALSE, results='asis'}
# DID
#employment
stark_nets1_emp$Type <- relevel(stark_nets1_emp$Type,ref = "Treatment: Stark & Oak")
stark_nets2_emp$Type <- relevel(stark_nets2_emp$Type,ref = "Treatment: Stark & Oak")

stark_nets1_emp_did <- did_agg_analysis(filter(stark_nets1_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stark_nets2_emp_did <- did_agg_analysis(filter(stark_nets2_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stargazer(stark_nets1_emp_did[[1]], stark_nets2_emp_did[[1]], stark_nets1_emp_did[[2]], stark_nets2_emp_did[[2]],
          stark_nets1_emp_did[[3]], stark_nets2_emp_did[[3]],
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business"), model.numbers = F)

# sales
stark_nets1_sales$Type <- relevel(stark_nets1_sales$Type,ref = "Treatment: Stark & Oak")
stark_nets2_sales$Type <- relevel(stark_nets2_sales$Type,ref = "Treatment: Stark & Oak")

stark_nets1_sales_did <- did_agg_analysis(filter(stark_nets1_sales, Type!="City" & year>2003), group = 1, endyear = 2010)
stark_nets2_sales_did <- did_agg_analysis(filter(stark_nets2_sales, Type!="City" & year>2003), group = 1, endyear = 2010)
stargazer(stark_nets1_sales_did[[1]], stark_nets2_sales_did[[1]], stark_nets1_sales_did[[2]], stark_nets2_sales_did[[2]], 
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

# show only Type 2 results
stargazer(stark_nets2_emp_did[[1]], stark_nets2_emp_did[[2]], stark_nets2_emp_did[[2]],
          stark_nets2_sales_did[[1]],  stark_nets2_sales_did[[2]], stark_nets2_sales_did[[3]],
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)
```


# ITS
```{r, echo=FALSE, results='asis'}
stark_nets1_emp <- stark_nets1_emp %>% mutate(Type = ifelse(Type=="Treatment: Stark & Oak", "Treatment", Type))
stark_nets2_emp <- stark_nets2_emp %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Stark & Oak", "Treatment", Type))
stark_nets1_sales <- stark_nets1_sales %>% 
  mutate(Type = ifelse(Type=="Treatment: Stark & Oak", "Treatment", Type))
stark_nets2_sales <- stark_nets2_sales %>% ungroup %>% 
  mutate(Type = ifelse(Type=="Treatment: Stark & Oak", "Treatment", Type))

stark_nets1_emp_its <- agg_its_analysis(filter(stark_nets1_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stark_nets2_emp_its <- agg_its_analysis(filter(stark_nets2_emp, Type!="City" & year>2003), group = 1, endyear = 2010)
stargazer(stark_nets1_emp_its[[1]], stark_nets2_emp_its[[1]], stark_nets1_emp_its[[2]], stark_nets2_emp_its[[2]], 
          stark_nets1_emp_its[[3]], stark_nets2_emp_its[[3]],
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2",  "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Emp.", "Food Emp.", "Business Emp."), model.numbers = F)

stark_nets1_sales$Type <- ifelse(stark_nets1_sales$Type=="Treatment: Stark & Oak", "Treatment", stark_nets1_sales$Type)
stark_nets1_sales$Type <- relevel(as.factor(stark_nets1_sales$Type),ref = "Treatment")

stark_nets2_sales$Type <- ifelse(stark_nets2_sales$Type=="Treatment: Stark & Oak", "Treatment", stark_nets2_sales$Type)
stark_nets2_sales$Type <- relevel(as.factor(stark_nets2_sales$Type),ref = "Treatment")

stark_nets1_sales_its <- agg_its_analysis(stark_nets1_sales, group = 1, endyear = 2010)
stark_nets2_sales_its <- agg_its_analysis(stark_nets2_sales, group = 1, endyear = 2010)
stargazer(stark_nets1_sales_its[[1]], stark_nets2_sales_its[[1]], stark_nets1_sales_its[[2]], stark_nets2_sales_its[[2]], 
          title = "Stark & Oak Avenue Corridor Difference-in-Difference Estimates", 
          column.labels  = c("Type 1", "Type 2", "Type 1","Type 2"), 
          type = "text", dep.var.labels = c("Retail Sales", "Food Sales"), model.numbers = F)

# show only Type 2 results
stargazer(stark_nets2_emp_its[[1]], stark_nets2_emp_its[[2]], stark_nets2_emp_its[[2]],
          stark_nets2_sales_its[[1]],  stark_nets2_sales_its[[2]], stark_nets2_sales_its[[3]],
          title = "Stark & Oak Avenue Corridor Interrupted Time Series Estimates", 
          column.labels  = c("Retail", "Food", "Business","Retail", "Food", "Business"), 
          type = "html", dep.var.labels = c("Employment","Employment","Employment","Sales", "Sales", "Sales"), model.numbers = F)

```

