---
title: "Indianapolis Trend Tables"
author: "Wei Shi"
date: "April 3, 2019"
output: html_document
---


```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, lubridate, dplyr, dbplyr, stargazer,cowplot, zoo, tidyr, kableExtra, data.table, bindrcpp, knitr, pander)


user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)


source(here::here("Code/corridor_comparison_functions.R"))

indy_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, b.name as Name, 
b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, 
b.grouptype as grouptype,  a.year as year, a.geom
FROM indy_lehd a, indy_corridors b
WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geom);")



#indy_corridor <- st_read(here::here("Data/Indianapolis/indy_corridor_lehd_NAD83.shp"))
indy_corridor <- indy_corridor %>% 
   rename(Type = grouptype) 
#add new colume of construct year as numeric

indy_corridor$Type <- as.character(indy_corridor$Type)
indy_corridor[indy_corridor$name =="Virginia Ave Comp. Corridor 1\n",]$Type <- "Control: Meridian"
indy_corridor[indy_corridor$name=="Virginia Ave Comp. Corridor 2\n",]$Type <- "Control: Prospect"
indy_corridor[indy_corridor$name=="Virginia Ave Comp. Corridor 3\n",]$Type <- "Control: Shelby"
indy_corridor[indy_corridor$name=="Mass Ave Comp. Corridor 1\n",]$Type <- "Control: Mass Ave"
indy_corridor$Type <- as.factor(indy_corridor$Type)

indy_corridor <- indy_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, Group = corridor_group,
         BuildStart = buildstart, BuildEnd = buildend, Name = name)

indy_lehd <- st_read(dsn = con, query = "SELECT * FROM indy_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19)



indy_sales <- dbReadTable(conn = con, name = "indy_sales_tax")
indy_sales <- indy_sales %>% 
  mutate(year = substr(quarter,1,4),
         Type = case_when(corridor=="Meridian" ~ "Control: Meridian",
                          corridor=="Prospect" ~ "Control: Prospect",
                          corridor=="Shelby" ~ "Control: Shelby",
                          corridor=="Mass Ave (control)" ~ "Control: Mass Ave",
                          TRUE ~ "Treatment")) %>% 
  group_by(corridor, year, group, Type) %>% 
  summarise(tax_revenue=sum(tax_revenue)) 

indy_qcew <- tbl(con, "indy_qcew_modified") %>% collect()
indy_qcew <- indy_qcew %>% 
  mutate(Type = case_when(corridor_name=="meridian" ~ "Control: Meridian",
                          corridor_name=="prospect" ~ "Control: Prospect",
                          corridor_name=="shelby" ~ "Control: Shelby",
                          corridor_name=="mass ave (control)" ~ "Control: Mass Ave",
                          TRUE ~ "Treatment")) %>% 
  group_by(year, Type, corridor_group, naics_code) %>% 
  summarise(employment = mean(employment,na.rm=T)) %>% filter(naics_code==722)

```

# functions
```{r message=FALSE, warning=FALSE, include=FALSE}
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}

lehd_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    select(Type, CNS07, CNS18) %>% 
  group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
          CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
            select(year, Type, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  lehd <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(lehd)<-coln

  return(lehd)
}


sales_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df <- df %>% mutate(CNS18=0) %>% rename(CNS07=tax_revenue)
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1), CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07,na.rm=T),0), CNS18=round(mean(CNS18,na.rm=T),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2) %>% 
            select(year, Type, CNS07, CNS18)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  sales <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(sales)<-coln

  return(sales)
}

qcew_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df <- df %>% rename(CNS07=avg_emp) %>% 
    group_by(year, Type) %>% 
    summarise(CNS07=mean(CNS07,na.rm=T)) %>% 
    mutate(CNS18=0, business=CNS07+CNS18) %>% select(year, Type, CNS07, CNS18, business) 
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    select(Type, CNS07, CNS18) %>% 
  group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
          CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
            select(year, Type, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  qcew <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) 

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(qcew)<-coln
  
  qcew[is.na(qcew)]<-NA
  qcew[qcew==0]<-NA

  return(qcew)
}

plot_t <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  group_rows("LEHD: (employment)",1,2) %>% 
  group_rows("Sales: (sales revenue, $)",3,4) %>% 
  group_rows("QCEW: (employment)",5,6) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))

  return(plot)

}

plot_tc <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

  return(plot)
}

```

# virginia
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

virginia_lehd <- agg_trend_table(indy_corridor, group = 1)

lehd <- lehd_t(virginia_lehd, 2011)


virginia_sale <- indy_sales %>% filter(group == 2) %>% 
  mutate(CNS18=0) %>% rename(CNS07=tax_revenue) %>% ungroup() %>% select(year, Type, CNS07, CNS18)
  
  base <- filter(virginia_sale, year%in%(2008:2010)) %>% 
    group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1), CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07,na.rm=T),0), CNS18=round(mean(CNS18,na.rm=T),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- virginia_sale %>% filter (year %in% c(2012:2014)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=2009) %>% 
          select(year, Type, CNS07, CNS18)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1), CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  sales <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent)
  
  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(sales)<-coln


virginia_qcew <- indy_qcew %>% filter(corridor_group==1&naics_code==722)  %>% 
  mutate(CNS07=0) %>% rename(CNS18=employment) %>% ungroup() %>% select(year, Type, CNS07, CNS18)

base <- filter(virginia_qcew, year%in%(2008:2010)) %>% 
    group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1), CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07,na.rm=T),0), CNS18=round(mean(CNS18,na.rm=T),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- virginia_qcew %>% filter (year %in% c(2012:2014)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=2009) %>% 
          select(year, Type, CNS07, CNS18)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1), CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  qcew <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(qcew)<-coln


# make combined table         
t <- rbind(lehd, sales, qcew)
t[t=="NaN"]<-NA
t[t==0]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,5,9),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,4) %>% 
  group_rows("Sales: [sales revenue]",5,8) %>% 
  group_rows("QCEW: [employment]",9,12) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))


t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",4), rep("Sales\n[sales revenue])",4),rep("QCEW\n[employment]",4)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,5,9),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

```


# mass ave
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

mass_lehd <- agg_trend_table(indy_corridor, group = 2)

lehd <- lehd_t(mass_lehd, 2009)

mass_sale <- indy_sales %>% filter(group == 1) %>% 
  mutate(CNS18=0) %>% rename(CNS07=tax_revenue) %>% ungroup() %>% select(year, Type, CNS07, CNS18)
  
  base <- filter(mass_sale, year==2008) %>% 
    group_by(Type) %>% 
  mutate(CNS07_base = NA, CNS18_base = NA) %>% 
  summarise(CNS07=round(mean(CNS07,na.rm=T),0), CNS18=round(mean(CNS18,na.rm=T),0), 
         CNS07_base = NA, CNS18_base = NA) 
  
  post <- mass_sale %>% filter (year %in% c(2010:2012)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=2007) %>% 
          select(year, Type, CNS07, CNS18)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1), CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  sales <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent)
  
  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(sales)<-coln




# make combined table         
t <- rbind(lehd, sales)
t[t=="NaN"]<-NA
t[t==0]<-NA

 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,3),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,2) %>% 
  group_rows("Sales: [sales revenue]",3,4) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))


t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",2), rep("Sales\n[sales revenue])",2)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,3),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

```
