---
title: "Memphis Trend Tables"
author: "Wei Shi"
date: "April 18, 2019"
output: html_document
---


```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, lubridate, dplyr, dbplyr, stargazer,cowplot, zoo, tidyr, kableExtra, data.table, bindrcpp, knitr, pander)


#query the corridors from bike_lanes
user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)

source(here::here("Code/corridor_comparison_functions.R"))

memphis_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns18 as cns18, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, 
a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, b.name as Name, 
b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, a.year as year, a.geometry
FROM memphis_lehd a, memhpis_corridors b
WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

cooper <- memphis_corridor %>% filter(name == "Cooper Street") %>% mutate(corridor_group =1)

memphis_corridor <-rbind(memphis_corridor, cooper)

memphis_corridor$Type <- ifelse(is.na(memphis_corridor$buildstart),"Control", "Treatment")
memphis_corridor[memphis_corridor$name =="Madison Avenue",]$Type <- "Treatment: Madison"
memphis_corridor[memphis_corridor$name =="Broad Avenue",]$Type <- "Treatment: Broad"
memphis_corridor[memphis_corridor$name =="Central Avenue",]$Type <- "Control: Central"
memphis_corridor[memphis_corridor$name=="Cooper Street",]$Type <- "Control: Cooper"
memphis_corridor[memphis_corridor$name=="Highland Street",]$Type <- "Control: Highland"
memphis_corridor[memphis_corridor$name=="Jackson Avenue",]$Type <- "Control: Jackson"
memphis_corridor[memphis_corridor$name=="Union Avenue",]$Type <- "Control: Union"
memphis_corridor$Type <- as.factor(memphis_corridor$Type)

memphis_corridor <- memphis_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, Group = corridor_group,
         BuildStart = buildstart, BuildEnd = buildend, Name = name)

memphis_lehd <- st_read(dsn = con, query = "SELECT * FROM memphis_lehd") %>% as.data.frame() %>% 
  rename(C000 = c000, CNS07 = cns07, CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,
         CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19)

memphis_emp_ratio <- employ_ratio_test(memphis_corridor)

memphis_growth <- growth_rate(memphis_corridor)


memphis_sales <- tbl(con, "memphis_sales_tax") %>% 
  collect()%>% 
  mutate(year = format(pctym, "%Y"),
         Type = paste(street_type, district_name, sep=": ")) %>% 
  group_by(year,district_name, street_type, street_group, Type) %>% 
  summarise(business = mean(businesses),
            gross_sales = sum(gross_sales))
  

memphis_qcew <- tbl(con, "memphis_qcew") %>% collect() %>% mutate(street_group = as.character(street_group))

# exclude Jackson corridor which is not comparable to treatment corridor
memphis_qcew <- memphis_qcew[memphis_qcew$district_name!="Jackson Ave",]

memphis_qcew$Type <- as.factor(memphis_qcew$Type)

dbDisconnect(con)

```

# functions
```{r message=FALSE, warning=FALSE, include=FALSE}
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}

lehd_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    select(Type, CNS07, CNS18) %>% 
  group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
          CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
            select(year, Type, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  lehd <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(lehd)<-coln

  return(lehd)
}


sales_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df <- df %>% mutate(CNS18=0) %>% rename(CNS07=gross_sales) %>% ungroup() %>% select(year, Type, CNS07, CNS18)
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1), CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07,na.rm=T),0), CNS18=round(mean(CNS18,na.rm=T),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2) %>% 
            select(year, Type, CNS07, CNS18)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  sales <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(sales)<-coln

  sales[is.na(sales)]<-NA
  sales[sales==0]<-NA
  
  return(sales)
}

qcew_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df <- df %>% rename(CNS07=emp_retail, CNS18=emp_food) %>% 
    group_by(year, Type) %>% 
    summarise(CNS07=mean(CNS07,na.rm=T),
              CNS18=mean(CNS18,na.rm=T)) %>% 
    mutate(business=CNS07+CNS18) %>% ungroup() %>% select(year, Type, CNS07, CNS18, business) 
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    select(Type, CNS07, CNS18) %>% 
  group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
          CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
            select(year, Type, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  qcew <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(qcew)<-coln

  return(qcew)
}

plot_t <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  group_rows("LEHD: (employment)",1,2) %>% 
  group_rows("Sales: (sales revenue, $)",3,4) %>% 
  group_rows("QCEW: (employment)",5,6) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))

  return(plot)

}

plot_tc <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

  return(plot)
}

```

# madison
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

madison_lehd <- agg_trend_table(memphis_corridor, group = 1) %>% filter(Type !="Control: Jackson")
lehd <- lehd_t(madison_lehd, 2011)

madison_sale <- filter(memphis_sales, street_group == 1) %>% filter(Type !="Control: Jackson Ave")
sales <- sales_t(madison_sale, 2011)

madison_qcew <- filter(memphis_qcew, street_group == 1) 
qcew <- qcew_t(madison_qcew, 2011)

# make combined table         
t <- rbind(lehd, sales, qcew)
t[t=="NaN"]<-NA
t[t==0]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,5,9),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,4) %>% 
  group_rows("Sales: [sales revenue]",5,8) %>% 
  group_rows("QCEW: [employment]",9,12) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))


t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",4), rep("Sales\n[sales revenue])",4),rep("QCEW\n[employment]",4)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,5,9),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

```


# broad
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

broad_lehd <- agg_trend_table(memphis_corridor, group = 2) 
lehd <- lehd_t(broad_lehd, 2010)

broad_sale <- filter(memphis_sales, street_group == 2) 
sales <- sales_t(broad_sale, 2010)

broad_qcew <- filter(memphis_qcew, street_group == 2) 
qcew <- qcew_t(broad_qcew, 2010)

# make combined table         
t <- rbind(lehd, sales, qcew)
t[t=="NaN"]<-NA
t[t==0]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,4,7),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,3) %>% 
  group_rows("Sales: [sales revenue]",4,6) %>% 
  group_rows("QCEW: [employment]",7,9) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))


t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",3), rep("Sales\n[sales revenue])",3),rep("QCEW\n[employment]",3)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,4,7),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))



```
