---
title: "seattle"
author: "Wei Shi"
date: "April 11, 2019"
output: html_document
---

```{r message=FALSE, warning=FALSE, include=FALSE}

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(here, RPostgreSQL, sf, ggplot2, directlabels,ggthemes, lubridate, dplyr, dbplyr, stargazer,cowplot, zoo, tidyr, kableExtra, data.table, bindrcpp, knitr, pander)


user <- "shiwei"
host <- "pgsql102.rc.pdx.edu"
pw <- scan(here::here("batteries.pgpss"), what = "")
dbname <- "bike_lanes"

con <- dbConnect("PostgreSQL", host = host, user = user, dbname = dbname, 
                 password = pw, port = 5433)


source(here::here("Code/corridor_comparison_functions.R"))
seattle_corridor <- st_read(dsn = con, query = "select a.geoid10 as geoid, a.c000 as c000,
a.cns07 as cns07, a.cns08 as cns08, a.cns12 as cns12, a.cns14 as cns14, a.cns15 as cns15, a.cns16 as cns16, a.cns17 as cns17, a.cns18 as cns18, a.cns19 as cns19, b.corr_name as Name, 
b.buildstart as buildstart, b.buildend as buildend, b.group as corridor_group, 
b.study_cont as grouptype,  a.year as year, a.geometry as geom
FROM seattle_lehd a, seattle_corridors b
WHERE ST_Intersects(ST_Buffer(b.geom, 20), a.geometry);")

seattle_corridor <- seattle_corridor %>%
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08,CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19, Group = corridor_group, BuildStart = buildstart, BuildEnd = buildend, Name = name, Type = grouptype, geometry = geom)
  
seattle_corridor <- seattle_corridor %>% 
  mutate(CNS07=ifelse(Name=="E Olive Way" & geoid==530330084003000 & year==2006, 5, CNS07)) # might be a data input error, replace it with average of the previous and next year


seattle_corridor$Type <- as.character(seattle_corridor$Type)
seattle_corridor[seattle_corridor$Name =="1st Ave",]$Type <- "Control: 1st Ave"
seattle_corridor[seattle_corridor$Name=="4th Ave",]$Type <- "Control: 4th Ave"
seattle_corridor[seattle_corridor$Name =="15th Ave E",]$Type <- "Control: 15th Ave E"
seattle_corridor[seattle_corridor$Name=="E Olive Way",]$Type <- "Control: E Olive Way"
seattle_corridor[seattle_corridor$Name=="University Way NE",]$Type <- "Control: University Way NE"
seattle_corridor[seattle_corridor$Name=="NE 45th St",]$Type <- "Control: NE 45th St"
seattle_corridor$Type <- as.factor(seattle_corridor$Type)

seattle_lehd <- st_read(dsn = con, "seattle_lehd") %>% as.data.frame() %>% 
  select(-geometry) %>% 
  rename(C000 = c000, CNS07 = cns07, CNS08 = cns08,CNS18 = cns18, CNS12 = cns12, CNS14 = cns14, CNS15 = cns15,CNS16 = cns16, CNS17 = cns17, CNS18 = cns18, CNS19 = cns19)

seattle_emp_ratio <- employ_ratio_test(seattle_corridor)

seattle_growth <- growth_rate(seattle_corridor)

# load qcew data
seattle_qcew <- tbl(con, "seattle_qcew") %>% collect()
replaceCommas<-function(x){
  x<-as.numeric(gsub("\\,", "", x))
}
seattle_qcew$employment <- replaceCommas(seattle_qcew$employment)

seattle_qcew <- seattle_qcew %>% spread(NACIS, employment) %>% 
  rename(Name = corridor, CNS07="44-45", CNS18="72") %>% 
  mutate(CNS07 = as.numeric(CNS07), CNS18 = as.numeric(CNS18), BuildStart = NA, BuildEnd=NA) %>% 
  mutate(BuildStart = case_when(Name=="2nd Avenue" ~ 2014,
                                Name=="Broadway" ~ 2013,
                                Name=="Roosevelt"~2016),
         BuildEnd = case_when(Name=="2nd Avenue" ~ 2014,
                                Name=="Broadway" ~ 2014,
                                Name=="Roosevelt"~2016))

seattle_qcew[seattle_qcew$Name =="1st Avenue",]$Type <- "Control: 1st Ave"
seattle_qcew[seattle_qcew$Name=="4th Avenue",]$Type <- "Control: 4th Ave"
seattle_qcew[seattle_qcew$Name =="15th Avenue",]$Type <- "Control: 15th Ave"
seattle_qcew[seattle_qcew$Name=="Olive Way",]$Type <- "Control: Olive Way"
seattle_qcew[seattle_qcew$Name=="University Way",]$Type <- "Control: University Way"
seattle_qcew[seattle_qcew$Name=="45th Street",]$Type <- "Control:45th St"
seattle_qcew$Type <- as.factor(seattle_qcew$Type)

```


# functions
```{r message=FALSE, warning=FALSE, include=FALSE}
percent <- function(x, digits = 2, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}

lehd_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    select(Type, CNS07, CNS18) %>% 
  group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
          CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
            select(year, Type, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  lehd <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(lehd)<-coln

  return(lehd)
}


sales_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df <- df %>% mutate(CNS18=0) %>% rename(CNS07=tax_revenue)
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1), CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07,na.rm=T),0), CNS18=round(mean(CNS18,na.rm=T),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2) %>% 
            select(year, Type, CNS07, CNS18)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  sales <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) %>% mutate_at(vars(contains("CNS18_")), percent)

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(sales)<-coln

  return(sales)
}

qcew_t <- function(df, construction_year){
  base_start= construction_year-3
  base_end = construction_year-1
  post_start=construction_year+1
  post_end=construction_year+3
  
  df <- df %>% rename(CNS07=avg_emp) %>% 
    group_by(year, Type) %>% 
    summarise(CNS07=mean(CNS07,na.rm=T)) %>% 
    mutate(CNS18=0, business=CNS07+CNS18) %>% select(year, Type, CNS07, CNS18, business) 
  
  base <- filter(df, year%in%(base_start:base_end)) %>% 
    select(Type, CNS07, CNS18) %>% 
  group_by(Type) %>% 
  mutate(CNS07_base = (CNS07/lag(CNS07)-1),
          CNS18_base = (CNS18/lag(CNS18)-1)) %>% 
  summarise(CNS07=round(mean(CNS07),0), CNS18=round(mean(CNS18),0), 
         CNS07_base = mean(CNS07_base,na.rm=T), CNS18_base = mean(CNS18_base,na.rm=T)) 
  
  post <- df %>% filter (year %in% c(post_start:post_end)) %>% ungroup() %>% 
    rbind(base %>% mutate(year=construction_year-2, business=CNS07+CNS18) %>% 
            select(year, Type, CNS07, CNS18, business)) %>% arrange(by_group=year) %>% 
    group_by(Type) %>% mutate(CNS07 = (CNS07/lag(CNS07)-1),CNS18 = (CNS18/lag(CNS18)-1))

  post <- dcast(setDT(post), Type ~ year, value.var = c("CNS07", "CNS18")) 
  post <- post[,-c(2,6)]
  post <- post %>% mutate(CNS07_post = rowMeans(select(.,starts_with("CNS07"))),
                          CNS18_post = rowMeans(select(.,starts_with("CNS18"))))

  qcew <- merge(base,post, by="Type") %>% 
    select(Type, CNS07,CNS07_base, starts_with("CNS07"),CNS18,CNS18_base, starts_with("CNS18")) %>%
    arrange(desc(Type)) %>% mutate_at(vars(contains("CNS07_")), percent) 

  coln <- c("Area", "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average",
          "Base","Growth", "1st Year", "2nd Year", "3rd Year","Average")
  names(qcew)<-coln
  
  qcew[is.na(qcew)]<-NA
  qcew[qcew==0]<-NA

  return(qcew)
}

plot_t <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  group_rows("LEHD: (employment)",1,2) %>% 
  group_rows("Sales: (sales revenue, $)",3,4) %>% 
  group_rows("QCEW: (employment)",5,6) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "1st year growth rate is defined as the growth rate of the year after construction compared to baseline."))

  return(plot)

}

plot_tc <- function(df){
  options(knitr.kable.NA = '-')
  plot <- knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,3,5),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of previous three years before construction year;",
             "Pre-growth rate is defined as average of baseline annual growth rate;",
             "Post-growth rate is defined as average annual growth rate of three time points after construction year."))

  return(plot)
}

```

# second
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

second_lehd <- agg_trend_table(seattle_corridor, group = 1)
pseudo2016 <- second_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2016, CNS07=NA, CNS18=NA, business=NA)
pseudo2017 <- second_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2017, CNS07=NA, CNS18=NA, business=NA)
pseudo2018 <- second_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2018, CNS07=NA, CNS18=NA, business=NA)
second_lehd <- bind_rows(second_lehd%>%ungroup()%>%mutate(year = as.numeric(year)), pseudo2016, pseudo2017, pseudo2018)
 
lehd <- lehd_t(second_lehd, 2014)


second_qcew <- agg_trend_table(seattle_qcew, group = 1)
qcew <- lehd_t(second_qcew, 2014)


# make combined table         
t <- rbind(lehd, qcew)
t[t=="NA%"]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,4),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,3) %>% 
  group_rows("QCEW: [employment]",4,6) %>% 
  footnote(number = c("Baseline is defined as the average of the three years prior to the construction year;",
             "Pre-growth rate is defined as the average of the baseline annual growth rates;",
             "Post-growth rate is defined as the average annual growth rate of three time points after the construction year"))



t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",3), rep("QCEW\n[employment]",3)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,4),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of the three years prior to the construction year;",
             "Pre-growth rate is defined as the average of the baseline annual growth rates;",
             "Post-growth rate is defined as the average annual growth rate of three time points after the construction year"))

```


# broadway
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

brdwy_lehd <- agg_trend_table(seattle_corridor, group = 2)
pseudo2016 <- brdwy_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2016, CNS07=NA, CNS18=NA, business=NA)
pseudo2017 <- brdwy_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2017, CNS07=NA, CNS18=NA, business=NA)
pseudo2018 <- brdwy_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2018, CNS07=NA, CNS18=NA, business=NA)
brdwy_lehd <- bind_rows(brdwy_lehd%>%ungroup()%>%mutate(year = as.numeric(year)), pseudo2016, pseudo2017, pseudo2018)
 
lehd <- lehd_t(brdwy_lehd, 2013)


brdwy_qcew <- agg_trend_table(seattle_qcew, group = 2)
qcew <- lehd_t(brdwy_qcew, 2013)


# make combined table         
t <- rbind(lehd, qcew)
t[t=="NA%"]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,4),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,3) %>% 
  group_rows("QCEW: [employment]",4,6) %>% 
  footnote(number = c("Baseline is defined as the average of the three years prior to the construction year;",
             "Pre-growth rate is defined as the average of the baseline annual growth rates;",
             "Post-growth rate is defined as the average annual growth rate of three time points after the construction year"))



t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",3), rep("QCEW\n[employment]",3)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,4),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of the three years prior to the construction year;",
             "Pre-growth rate is defined as the average of the baseline annual growth rates;",
             "Post-growth rate is defined as the average annual growth rate of three time points after the construction year"))

```


# roosevelt
```{r, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}

roos_lehd <- agg_trend_table(seattle_corridor, group = 3)
pseudo2016 <- roos_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2016, CNS07=NA, CNS18=NA, business=NA)
pseudo2017 <- roos_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2017, CNS07=NA, CNS18=NA, business=NA)
pseudo2018 <- roos_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2018, CNS07=NA, CNS18=NA, business=NA)
pseudo2019 <- roos_lehd[c(1:3),]%>% ungroup()%>%
  mutate(year = 2019, CNS07=NA, CNS18=NA, business=NA)
roos_lehd <- bind_rows(roos_lehd%>%ungroup()%>%mutate(year = as.numeric(year)), pseudo2016, pseudo2017, pseudo2018, pseudo2019)
 
lehd <- lehd_t(roos_lehd, 2016)


roos_qcew <- agg_trend_table(seattle_qcew, group = 3)
pseudo2018 <- roos_qcew[c(1:3),]%>% ungroup()%>%
  mutate(year = 2018, CNS07=NA, CNS18=NA, business=NA)
pseudo2019 <- roos_qcew[c(1:3),]%>% ungroup()%>%
  mutate(year = 2019, CNS07=NA, CNS18=NA, business=NA)
roos_qcew <- bind_rows(roos_qcew%>%ungroup()%>%mutate(year = as.numeric(year)),pseudo2018, pseudo2019)
qcew <- lehd_t(roos_qcew, 2016)


# make combined table         
t <- rbind(lehd, qcew)
t[t=="NA%"]<-NA
 
options(knitr.kable.NA = '-')
  knitr::kable(t, align = "lcccccccccccc",  format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","Baseline"=2,"Post-implementation"=4,"Baseline"=2,"Post-implementation"=4)) %>% 
  add_header_above(c("", "Retail"= 6, "Food"= 6)) %>% 
  row_spec(c(1,4),background="#ccffcc") %>% 
  group_rows("LEHD: [employment]",1,3) %>% 
  group_rows("QCEW: [employment]",4,6) %>% 
  footnote(number = c("Baseline is defined as the average of the three years prior to the construction year;",
             "Pre-growth rate is defined as the average of the baseline annual growth rates;",
             "Post-growth rate is defined as the average annual growth rate of three time points after the construction year"))



t_c <- t[c(1:3,7:9,13)] 
data <- data.frame(c(rep("LEHD\n[employment]",3), rep("QCEW\n[employment]",3)))
t_c <- bind_cols(data, t_c)
coln <- c("Data","Area", "Baseline","Pre-Growth", "Post-Growth","Baseline","Pre-Growth", "Post-Growth")
names(t_c)<-coln

options(knitr.kable.NA = '-')
  knitr::kable(t_c, align = "llcccccc", format.args = list(big.mark = ",")) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "condensed"), full_width=F, font_size=11) %>% 
  add_header_above(c("","", "Retail"= 3, "Food"= 3)) %>% 
  row_spec(c(1,4),background="#ccffcc") %>% 
  column_spec(1, bold=T,background="white", width="0.5in") %>% 
  collapse_rows(columns=1) %>% 
  footnote(number = c("Baseline is defined as the average of the three years prior to the construction year;",
             "Pre-growth rate is defined as the average of the baseline annual growth rates;",
             "Post-growth rate is defined as the average annual growth rate of three time points after the construction year"))

```


# trend plot functions
```{r, echo=FALSE, echo=FALSE, message=FALSE, warning=FALSE}

#Define functions: agg_index_trend_table, trend_agg_plot_LEHD, trend_agg_index_plot_LEHD, trend_agg_index_plot_city_LEHD

#agg_index_trend_table
agg_index_trend_table <- function(df, group, construct_year) {
  
  #prepare tables for plotting
  df <- as.data.frame(df, stringsAsFactors = FALSE)
  
  df <- df %>% filter(Group == group) %>% mutate(business = CNS07+CNS18)
  
  start= construct_year-3
  end=construct_year-1
  

  df_agg <- df %>% group_by(year, Type) %>%
    summarise(CNS07 = sum(CNS07, na.rm = TRUE),
              CNS18 = sum(CNS18, na.rm = TRUE),
              business = sum(business, na.rm = TRUE))
  
  base_year <-  df_agg %>% filter(year %in% c(start:end)) %>% group_by(Type) %>% 
    summarise(CNS07_base = mean(CNS07), CNS18_base = mean(CNS18), business_base = mean(business))
  
  
  df_plot <- df_agg %>%  
    left_join(base_year, by = "Type") %>%
    mutate(CNS07_sd = CNS07/CNS07_base*100,
           CNS18_sd = CNS18/CNS18_base*100,
           business_sd = business/business_base*100) %>%
    select(Type, year = year, CNS07_sd, CNS18_sd, business_sd) %>% filter(!is.na(CNS07_sd))
  
  return(df_plot)
  
}

city_agg_index_trend_table <- function(df, construct_year) {
  
  if(class(df) == "sf") {
    
    df <- as.data.frame(df, stringsAsFactors = FALSE)
    
  } else {
    
    df
  }
  
  df <- df %>% mutate(business = CNS07 + CNS18)
  
  start= construct_year-3
  end=construct_year-1
  
  df_agg <- df %>% group_by(year) %>%
    summarise(CNS07 = sum(CNS07),
              CNS18 = sum(CNS18),
              business = sum(business)) %>% 
    mutate(Type = "city")
  
  base_year <-  df_agg %>% filter(year %in% c(start:end)) %>% group_by(Type) %>% 
    summarise(CNS07_base = mean(CNS07), CNS18_base = mean(CNS18), business_base = mean(business))
  
  df_plot <- df_agg %>%  
    left_join(base_year,by="Type") %>%
    mutate(CNS07_sd = CNS07/CNS07_base*100,
           CNS18_sd = CNS18/CNS18_base*100,
           business_sd = business/business_base*100,
           Type = "city") %>%
    select(Type, year, CNS07_sd, CNS18_sd, business_sd) %>% filter(!is.na(CNS07_sd))
  
  return(df_plot)
  
}


#trend_agg_plot_LEHD

trend_agg_plot_LEHD <- function(df_plot, base, industry, corridor_name, control_corridor, 
                                      industry_code = c("CNS07", "CNS18", "business"), 
                                      construct_year, end_year, construct_year2, end_year2) {

  ##convert year to proper date
  
  df_plot$year <-as.character(paste0(df_plot$year, "-01-01"))
  df_plot$year <- as.Date(df_plot$year, "%Y-%m-%d")
  
  construct_date <- as.character(paste0(construct_year-1, "-07-01"))
  construct_date <- as.Date(construct_date, "%Y-%m-%d")
  
  end_date <- as.character(paste0(end_year-1, "-07-01"))
  end_date <- as.Date(end_date, "%Y-%m-%d")
  
  construct_date2 <- as.character(paste0(construct_year-4, "-07-01"))
  construct_date2 <- as.Date(construct_date2, "%Y-%m-%d")
  
  end_date2 <- as.character(paste0(end_year-2, "-07-01"))
  end_date2 <- as.Date(end_date2, "%Y-%m-%d")
  
  ##making the plot
  
  ats_df <- ggplot(df_plot, aes(x = year, y = get(industry_code), 
                                group = Type, colour = Type, shape=Type)) + 
    geom_line()  +
    geom_rect(aes(xmin = as.Date(construct_date, "%Y"), 
                  xmax = as.Date(end_date, "%Y"), 
                  ymin = -Inf, ymax = Inf),
              fill = "#adff2f",linetype=0,alpha = 0.03) +
    
    geom_rect(aes(xmin = as.Date(construct_date2, "%Y"), 
                  xmax = as.Date(end_date2, "%Y"), 
                  ymin = -Inf, ymax = Inf),
              fill = "grey",linetype=0,alpha = 0.03) +
    
    geom_point(size = 3, fill="white") +
    scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
    theme_minimal() +
    labs(title = glue("{industry} {base} Comparison:\n {corridor_name}"), x="Year",y={base},
         caption = glue("Gray shaded area is pre-construction period\n Green shaded area is construction period")) + guides(title = "Street Type") 
  
  return(ats_df)
}


#trend_agg_index_plot_LEHD

trend_agg_index_plot_LEHD <- function(df_plot, base, industry, corridor_name, control_corridor, 
                                      industry_code = c("CNS07_sd", "CNS18_sd", "business_sd"), 
                                      construct_year, end_year, construct_year2, end_year2) {

  ##convert year to proper date
  
  df_plot$year <-as.character(paste0(df_plot$year, "-01-01"))
  df_plot$year <- as.Date(df_plot$year, "%Y-%m-%d")
  
  construct_date <- as.character(paste0(construct_year-1, "-07-01"))
  construct_date <- as.Date(construct_date, "%Y-%m-%d")
  
  end_date <- as.character(paste0(end_year-1, "-07-01"))
  end_date <- as.Date(end_date, "%Y-%m-%d")
  
  construct_date2 <- as.character(paste0(construct_year-4, "-07-01"))
  construct_date2 <- as.Date(construct_date2, "%Y-%m-%d")
  
  end_date2 <- as.character(paste0(end_year-2, "-07-01"))
  end_date2 <- as.Date(end_date2, "%Y-%m-%d")
  
  ##making the plot
  
  ats_df <- ggplot(df_plot, aes(x = year, y = get(industry_code), 
                                group = Type, colour = Type, shape=Type)) + 
    geom_line()  +
    geom_rect(aes(xmin = as.Date(construct_date, "%Y"), 
                  xmax = as.Date(end_date, "%Y"), 
                  ymin = -Inf, ymax = Inf),
              fill = "#adff2f",linetype=0,alpha = 0.03) +
    
    geom_rect(aes(xmin = as.Date(construct_date2, "%Y"), 
                  xmax = as.Date(end_date2, "%Y"), 
                  ymin = -Inf, ymax = Inf),
              fill = "grey",linetype=0,alpha = 0.03) +
    
    geom_point(size = 3, fill="white") +
    scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
    theme_minimal() +
    labs(title = glue("{industry} {base} Comparison:\n {corridor_name}"), x="Year",y=paste({base}," Index"),
         caption = glue("Gray shaded area is pre-construction period\n Green shaded area is construction period\n {base} is indexed to the baseline years (3 years pre-construction)")) + guides(title = "Street Type") 
  
  return(ats_df)
}


#trend_agg_index_plot_city_LEHD
trend_agg_index_plot_city_LEHD <- function(df_plot, base, industry, corridor_name, control_corridor, 
                                      industry_code = c("CNS07_sd", "CNS18_sd", "business_sd"), 
                                      construct_year, end_year, construct_year2, end_year2) {
  
  df_plot <- df_plot %>% 
    mutate(Type = case_when(Type == "improvement" ~ "Treatment",
                            Type == "control" ~ paste0("Control: ", control_corridor),
                            Type == "city" ~ "City"))

  df_plot$Type <- factor(df_plot$Type, 
                       levels = c("Treatment", paste0("Control: ", control_corridor), "City"))

  ##convert year to proper date
  
  df_plot$year <-as.character(paste0(df_plot$year, "-01-01"))
  df_plot$year <- as.Date(df_plot$year, "%Y-%m-%d")
  
  construct_date <- as.character(paste0(construct_year-1, "-07-01"))
  construct_date <- as.Date(construct_date, "%Y-%m-%d")
  
  end_date <- as.character(paste0(end_year-1, "-07-01"))
  end_date <- as.Date(end_date, "%Y-%m-%d")
  
  construct_date2 <- as.character(paste0(construct_year-4, "-07-01"))
  construct_date2 <- as.Date(construct_date2, "%Y-%m-%d")
  
  end_date2 <- as.character(paste0(end_year-2, "-07-01"))
  end_date2 <- as.Date(end_date2, "%Y-%m-%d")
  
  ##making the plot
  
  ats_df <- ggplot(df_plot, aes(x = year, y = get(industry_code), 
                                group = Type, colour = Type, shape=Type)) + 
    geom_line()  +
    geom_rect(aes(xmin = as.Date(construct_date, "%Y"), 
                  xmax = as.Date(end_date, "%Y"), 
                  ymin = -Inf, ymax = Inf),
                  fill = "#adff2f",linetype=0,alpha = 0.03) +
    
    geom_rect(aes(xmin = as.Date(construct_date2, "%Y"), 
                  xmax = as.Date(end_date2, "%Y"), 
                  ymin = -Inf, ymax = Inf),
                  fill = "grey",linetype=0,alpha = 0.03) +
    
    geom_point(size = 3, fill="white") +
    scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
    theme_minimal() +
    labs(title = glue("{industry} {base} Comparison:\n {corridor_name}"), x="Year", y=paste({base}," Index"),
         caption = glue("Gray shaded area is pre-construction period\n Green shaded area is construction period\n {base} is indexed to the baseline years (3 years pre-construction)")) + guides(title = "Street Type") 
  
  return(ats_df)
}

```

# Second Ave
## non-index LEHD
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}

secondave_agg <- agg_trend_table(seattle_corridor, group = 1)
secondave_agg$Type <- factor(as.character(secondave_agg$Type), levels =c("Study","Control: 1st Ave", "Control: 4th Ave"),
                             labels = c("Treatment", "Control: 1st Ave", "Control: 4th Ave"))
agg_retail_trend_plot <- trend_agg_plot_LEHD(secondave_agg, base="Employment", industry = "Retail", industry_code = "CNS07", corridor_name = "Second Ave.", construct_year = 2014, end_year = 2015, construct_year2=2011, end_year2=2014)
agg_food_trend_plot <- trend_agg_plot_LEHD(secondave_agg, base="Employment",industry = "Food",industry_code = "CNS18", corridor_name = "Second Ave.", construct_year = 2014, end_year = 2015, construct_year2=2011, end_year2=2014)

prow <- plot_grid(agg_retail_trend_plot + theme(legend.position="none"),
                 agg_food_trend_plot + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 1)

legend_b <- get_legend(agg_food_trend_plot + theme(legend.position="bottom"))
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

## index LEHD
```{r, fig.width = 10, echo=FALSE, message=FALSE, warning=FALSE, fig.height= 5}

#second index table and plot
second_agg_idx <- agg_index_trend_table(seattle_corridor, group = 1, construct_year = 2014)

#city agg plots
seattle_agg <- city_agg_index_trend_table(seattle_lehd, construct_year = 2014)

second_agg_idx <- bind_rows(second_agg_idx, seattle_agg)

second_agg_idx$Type <- factor(as.character(second_agg_idx$Type), levels =c("Study","Control: 1st Ave", "Control: 4th Ave", "city"),
                             labels = c("Treatment", "Control: 1st Ave", "Control: 4th Ave", "City"))

second_agg_retail <- trend_agg_index_plot_LEHD(second_agg_idx, base = "Employment", industry = "Retail",
                                                       corridor_name = "Second Ave.", control_corridor = "Cedar Ave.",
                                                       industry_code = "CNS07_sd", construct_year = 2014, end_year = 2015)

second_agg_accom <- trend_agg_index_plot_LEHD(second_agg_idx, base = "Employment", industry = "Food",
                                                      corridor_name = "Second Ave.", control_corridor = "Cedar Ave.",
                                                      industry_code = "CNS18_sd", construct_year = 2014, end_year = 2015)

prow <- plot_grid(second_agg_retail + theme(legend.position="none"),
                  second_agg_accom + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 1)

legend_b <- get_legend(second_agg_retail + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

##QCEW
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=9.5, fig.asp=1}
second_q <- filter(seattle_qcew, Group==1)
second_q$Type <- factor(as.character(second_q$Type), 
                              levels =c("Treatment","Control: 1st Ave", "Control: 4th Ave"),
                             labels = c("Treatment", "Control: 1st Ave", "Control: 4th Ave"))

agg_retail_trend_plot <- trend_agg_plot_LEHD(second_q, base="Employment", industry = "Retail", industry_code = "CNS07", corridor_name = "Second Ave.", construct_year = 2014, end_year = 2015, construct_year2=2011, end_year2=2014)
agg_food_trend_plot <- trend_agg_plot_LEHD(second_q, base="Employment",industry = "Food",industry_code = "CNS18", corridor_name = "Second Ave.", construct_year = 2014, end_year = 2015, construct_year2=2011, end_year2=2014)

second <- agg_index_trend_table(seattle_qcew %>% mutate(geometry=0), group=1, construct_year = 2014) 

second$Type <- factor(as.character(second$Type), 
                              levels =c("Treatment","Control: 1st Ave", "Control: 4th Ave"),
                             labels = c("Treatment", "Control: 1st Ave", "Control: 4th Ave"))

second_agg_retail <- trend_agg_index_plot_LEHD(second, base = "Employment", industry = "Retail",
                                              corridor_name = "Second Ave.", control_corridor = "Cedar Ave.",
                                              industry_code = "CNS07_sd", construct_year = 2014, end_year = 2015)

second_agg_food <- trend_agg_index_plot_LEHD(second, base = "Employment", industry = "Food",
                                                      corridor_name = "Second Ave.", control_corridor = "Cedar Ave.",
                                                      industry_code = "CNS18_sd", construct_year = 2014, end_year = 2015)

prow <- plot_grid(agg_retail_trend_plot + theme(legend.position="none"), 
                  agg_food_trend_plot + theme(legend.position="none"), 
                  second_agg_retail + theme(legend.position="none"),
                  second_agg_food + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 2)

legend_b <- get_legend(second_agg_retail + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(4, .2))
```

# broadway
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}

brdwy_agg <- agg_trend_table(seattle_corridor, group = 2)
brdwy_agg$Type <- factor(as.character(brdwy_agg$Type), levels =c("Study","Control: 15th Ave E", "Control: E Olive Way"),
                             labels = c("Treatment", "Control: 15th Ave", "Control: Olive Way"))
agg_retail_trend_plot <- trend_agg_plot_LEHD(brdwy_agg, base="Employment", industry = "Retail", industry_code = "CNS07", corridor_name = "Broadway", construct_year = 2013, end_year = 2014, construct_year2=2010, end_year2=2013)
agg_food_trend_plot <- trend_agg_plot_LEHD(brdwy_agg, base="Employment",industry = "Food",industry_code = "CNS18", corridor_name = "Broadway", construct_year = 2013, end_year = 2014, construct_year2=2010, end_year2=2013)

prow <- plot_grid(agg_retail_trend_plot + theme(legend.position="none"),
                 agg_food_trend_plot + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 1)

legend_b <- get_legend(agg_food_trend_plot + theme(legend.position="bottom"))
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

## index LEHD
```{r, fig.width = 10, echo=FALSE, message=FALSE, warning=FALSE, fig.height= 5}

#second index table and plot
brdwy_agg_idx <- agg_index_trend_table(seattle_corridor, group = 2, construct_year = 2013)

#city agg plots
seattle_agg <- city_agg_index_trend_table(seattle_lehd, construct_year = 2013)

brdwy_agg_idx <- bind_rows(brdwy_agg_idx, seattle_agg)

brdwy_agg_idx$Type <- factor(as.character(brdwy_agg_idx$Type), 
                             levels =c("Study","Control: 15th Ave E", "Control: E Olive Way", "city"),
                             labels = c("Treatment", "Control: 15th Ave", "Control: Olive Way","City"))

brdwy_agg_retail <- trend_agg_index_plot_LEHD(brdwy_agg_idx, base = "Employment", industry = "Retail",
                                                       corridor_name = "Broadway", control_corridor = "Cedar Ave.",
                                                       industry_code = "CNS07_sd", construct_year = 2013, end_year = 2014)

brdwy_agg_accom <- trend_agg_index_plot_LEHD(brdwy_agg_idx, base = "Employment", industry = "Food",
                                                      corridor_name = "Broadway", control_corridor = "Cedar Ave.",
                                                      industry_code = "CNS18_sd", construct_year = 2013, end_year = 2014)

prow <- plot_grid(brdwy_agg_retail + theme(legend.position="none"),
                  brdwy_agg_accom + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 1)

legend_b <- get_legend(brdwy_agg_retail + theme(legend.position="bottom"))

plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```

##QCEW
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=9.5, fig.asp=1}
brdwy_q <- filter(seattle_qcew, Group==2)
brdwy_q$Type <- factor(as.character(brdwy_q$Type), 
                              levels =c("Treatment","Control: 15th Ave", "Control: Olive Way"))

agg_retail_trend_plot <- trend_agg_plot_LEHD(brdwy_q, base="Employment", industry = "Retail", industry_code = "CNS07", corridor_name = "Broadway", construct_year = 2013, end_year = 2014, construct_year2=2010, end_year2=2013)
agg_food_trend_plot <- trend_agg_plot_LEHD(brdwy_q, base="Employment",industry = "Food",industry_code = "CNS18", corridor_name = "Broadway",construct_year = 2013, end_year = 2014, construct_year2=2010, end_year2=2013)

brdwy <- agg_index_trend_table(seattle_qcew %>% mutate(geometry=0), group=2, construct_year = 2013) 

brdwy$Type <- factor(as.character(brdwy$Type), 
                              levels =c("Treatment","Control: 15th Ave", "Control: Olive Way"))

brdwy[brdwy==0] <- NA

brdwy_agg_retail <- trend_agg_index_plot_LEHD(brdwy, base = "Employment", industry = "Retail",
                                              corridor_name = "Broadway", control_corridor = "Cedar Ave.",
                                              industry_code = "CNS07_sd", construct_year = 2013, end_year = 2014)

brdwy_agg_food <- trend_agg_index_plot_LEHD(brdwy, base = "Employment", industry = "Food",
                                                      corridor_name = "Broadway", control_corridor = "Cedar Ave.",
                                                      industry_code = "CNS18_sd", construct_year = 2013, end_year = 2014)

prow <- plot_grid(agg_retail_trend_plot + theme(legend.position="none"), 
                  agg_food_trend_plot + theme(legend.position="none"), 
                  brdwy_agg_retail + theme(legend.position="none"),
                  brdwy_agg_food + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 2)

legend_b <- get_legend(brdwy_agg_retail + theme(legend.position="bottom"))

plot_grid( prow, legend_b, ncol = 1, rel_heights = c(4, .2))
```


# roosevelt
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 9.5, fig.asp=.5}

roos_agg <- agg_trend_table(seattle_corridor, group = 3)
roos_agg$Type <- factor(as.character(roos_agg$Type), levels =c("Study","Control: NE 45th St", "Control: University Way NE"),
                             labels = c("Treatment", "Control: 45th St", "Control: University Way"))
agg_retail_trend_plot <- trend_agg_plot_LEHD(roos_agg, base="Employment", industry = "Retail", industry_code = "CNS07", corridor_name = "Roosevelt Way", construct_year = 2016, end_year = 2017, construct_year2=2013, end_year2=2016)
agg_food_trend_plot <- trend_agg_plot_LEHD(roos_agg, base="Employment",industry = "Food",industry_code = "CNS18", corridor_name = "Roosevelt Way", construct_year = 2016, end_year = 2017, construct_year2=2013, end_year2=2016)

prow <- plot_grid(agg_retail_trend_plot + theme(legend.position="none"),
                 agg_food_trend_plot + theme(legend.position="none"),
                  align = 'vh', hjust = -1, nrow = 1)

legend_b <- get_legend(agg_food_trend_plot + theme(legend.position="bottom"))
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(4, .2))

```